/**
 * Barnes & Noble — ABM Microsite Data
 * Quality Tier: B
 * Generated by scripts/generate-microsite-data.ts
 * 
 * Sources:
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (5 named contacts)
 */

import type { AccountMicrositeData } from '../schema';

const BOOKING_LINK = 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2UyZRVDBYFwV3QOTx7-WK4APujmADpAGspAqeR5qAmK4KJjN2P1QNIrsVj0SPO0qMZIWKzuPoW';

// LEGACY SECTIONS (preserved for reference — M3.2-M3.6 may lift prose into memo sections)
/*
 * [
 *     {
 *       type: 'hero',
 *       headline: 'Barnes and Noble\'s supply chain leader is speaking at MODEX. Their DCs move 500+ trailers a day to restock 600 stores. We should meet.',
 *       subheadline: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
 *       accountCallout: 'Barnes & Noble - Retail',
 *       backgroundTheme: 'dark',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Barnes & Noble',
 *         subtext: '30-minute walk-through of your facility network with board-ready ROI.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *     },
 *     {
 *       type: 'problem',
 *       sectionLabel: 'The Hidden Constraint',
 *       headline: 'The yard is where Barnes & Noble\'s supply chain math breaks down',
 *       narrative: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
 *       painPoints: [
 *         {
 *           headline: 'Retail book replenishment operates on razor-thin timing windows',
 *           description: 'Barnes and Noble restocks 600+ stores from 8 distribution centers. Book releases are date-sensitive, and inventory replenishment windows are measured in days. When the yard backs up at a DC, store shelves go empty on release day.',
 *           kpiImpact: 'New release availability tied directly to DC-level dock turn performance',
 *           relevantPeople: ['barnes-noble-danek-akey', 'barnes-noble-huggan'],
 *         },
 *         {
 *           headline: 'E-commerce and store replenishment competing for the same dock doors',
 *           description: 'Barnes and Noble ships to stores and ships to customers from the same DCs. Store replenishment loads and e-commerce parcel picks compete for dock doors and yard space. Without yard-level prioritization, both channels suffer.',
 *           kpiImpact: 'Dual-channel DC operations without yard-level channel prioritization',
 *           relevantPeople: ['barnes-noble-danek-akey', 'barnes-noble-huggan'],
 *         },
 *         {
 *           headline: 'Named MODEX speaker signals active supply chain investment evaluation',
 *           description: 'VP Supply Chain Annette Danek-Akey is a named session speaker at MODEX 2026. When supply chain leadership presents at the industry\'s largest event, they are signaling openness to new solutions and partnerships.',
 *           kpiImpact: 'Direct meeting path: speaker attendance = high probability of floor presence',
 *           relevantPeople: ['barnes-noble-danek-akey', 'barnes-noble-huggan'],
 *         }
 *       ],
 *     },
 *     {
 *       type: 'stakes',
 *       sectionLabel: 'What This Costs You',
 *       headline: 'The math Barnes & Noble is not tracking in one place',
 *       narrative: 'Barnes and Noble restocks 600+ stores from 8 distribution centers. Book releases are date-sensitive, and inventory replenishment windows are measured in days. When the yard backs up at a DC, store shelves go empty on release day. Meanwhile, barnes and Noble ships to stores and ships to customers from the same DCs. Store replenishment loads and e-commerce parcel picks compete for dock doors and yard space. Without yard-level prioritization, both channels suffer.',
 *       annualCost: '$5M-$8M in estimated yard-driven inefficiency across the network',
 *       costBreakdown: [
 *         { label: 'Carrier detention / demurrage', value: '$2M+' },
 *         { label: 'Dock contention and turn time excess', value: '$2M+' },
 *         { label: 'Gate and spotter labor overhead', value: '$2M+' },
 *         { label: 'Peak season surge inefficiency', value: '$1M+' },
 *       ],
 *       urgencyDriver: 'Named session speaker indicates event involvement.',
 *     },
 *     {
 *       type: 'solution',
 *       sectionLabel: 'The Fix',
 *       headline: 'One protocol across every Barnes & Noble yard',
 *       narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Same driver journey at every facility. same dock assignment logic. Variance dies. Throughput becomes calculable.',
 *       modules: [
 *         { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Standardizes verify across Barnes & Noble\'s facility network.' },
 *         { id: 'flowBOL', name: 'flowBOL', verb: 'Document', shortDescription: 'Touchless BOL creation with timestamped chain of custody.', relevanceToAccount: 'Standardizes document across Barnes & Noble\'s facility network.' },
 *         { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. No more radio dispatching.', relevanceToAccount: 'Standardizes execute across Barnes & Noble\'s facility network.' },
 *         { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Standardizes map across Barnes & Noble\'s facility network.' },
 *       ],
 *       accountFit: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
 *     },
 *     {
 *       type: 'proof',
 *       sectionLabel: 'Proof from Live Deployment',
 *       headline: 'Running today across 24 facilities',
 *       blocks: [
 *         {
 *           type: 'metric',
 *           stats: [
 *             { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol at comparable retail operations' },
 *             { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across similar verticals' },
 *             { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
 *             { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at retail facilities' },
 *           ],
 *         },
 *         {
 *           type: 'quote',
 *           quote: {
 *             text: 'The yard used to be where we lost visibility. Now it is where we gain control over every trailer in the network. The dock office runs itself.',
 *             role: 'Operations Director',
 *             company: 'National Retail Distributor',
 *           },
 *         },
 *       ],
 *     },
 *     {
 *       type: 'network-map',
 *       sectionLabel: 'Your Network',
 *       headline: 'Barnes & Noble\'s yard network at scale',
 *       narrative: 'Every one of these facilities runs its own yard protocol today. Different gate processes, different spotter dispatch methods, different tribal knowledge. YardFlow gives you one standard across all of them.',
 *       facilityCount: '8',
 *       facilityTypes: ['Regional Distribution Centers', 'E-commerce Fulfillment Centers'],
 *       geographicSpread: 'North America',
 *       dailyTrailerMoves: '500+ across the network',
 *     },
 *     {
 *       type: 'roi',
 *       sectionLabel: 'The Business Case',
 *       headline: 'Conservative ROI model for Barnes & Noble',
 *       narrative: 'Based on measured YardFlow improvements at comparable operations.',
 *       roiLines: [
 *         { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
 *         { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
 *         { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
 *         { label: 'Dock utilization', before: '65%', after: '85%', delta: '+20 pts', unit: 'utilization' },
 *       ],
 *       totalAnnualSavings: '$5M-$8M across the network',
 *       paybackPeriod: '< 6 months',
 *       methodology: 'Based on measured results at 24 live facilities extrapolated to Barnes & Noble facility count and operational profile.',
 *     },
 *     {
 *       type: 'testimonial',
 *       sectionLabel: 'From an Operator Who Runs It',
 *       quote: 'Before YardFlow, we had 30 trailers in the yard and no idea which ones were loaded. Now every trailer has a status and a plan.',
 *       role: 'Operations Director',
 *       company: 'National Retail Distributor',
 *       context: 'After 12 months of full YardFlow deployment across their facility network.',
 *     },
 *     {
 *       type: 'cta',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Barnes & Noble',
 *         subtext: 'We map your top 3 facilities, identify the throughput constraint, and build a board-ready rollout plan.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *       closingLine: 'One conversation. Your yard network. A clear path to $5M-$8M in annual savings.',
 *     },
 *   ]
 */

export const barnesNoble: AccountMicrositeData = {
  slug: 'barnes-noble',
  accountName: 'Barnes & Noble',
  parentBrand: 'Barnes & Noble',
  vertical: 'retail',
  tier: 'Tier 3',
  band: 'D',
  priorityScore: 55,

  pageTitle: 'YardFlow for Barnes & Noble - Yard Network Standardization',
  metaDescription: 'How YardFlow eliminates the yard bottleneck across Barnes & Noble\'s facility network.',

  sections: [],

  people: [
    {
      personaId: 'P-066',
      name: 'Annette Danek-Akey',
      firstName: 'Annette',
      lastName: 'Danek-Akey',
      title: 'Chief Supply Chain Officer',
      company: 'Barnes & Noble',
      email: 'annette.danek-akey@bn.com',
      linkedinUrl: 'https://www.barnesandnobleinc.com/management/annette-danek-akey/',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Supply Chain',
      currentMandate: 'Official Barnes & Noble supply-chain chief and MODEX speaker.',
      bestIntroPath: 'Conference / executive outreach',
    },
    {
      personaId: 'P-067',
      name: 'John Huggan',
      firstName: 'John',
      lastName: 'Huggan',
      title: 'Senior Director Logistics',
      company: 'Barnes & Noble',
      email: 'john.huggan@bn.com',
      linkedinUrl: 'https://www.linkedin.com/in/john-huggan-ba6430179',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Distribution Center Operations',
      currentMandate: 'Named senior logistics leader at Barnes & Noble.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-068',
      name: 'Joe Marmorato',
      firstName: 'Joe',
      lastName: 'Marmorato',
      title: 'Senior Manager, Fulfillment Operations',
      company: 'Barnes & Noble',
      email: 'joe.marmorato@bn.com',
      linkedinUrl: 'https://www.linkedin.com/in/joe-marmorato-73a4854',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Transportation / Fulfillment',
      currentMandate: 'Named omnichannel fulfillment operator.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-069',
      name: 'Yobanny Lopez',
      firstName: 'Yobanny',
      lastName: 'Lopez',
      title: 'Senior Warehouse Operations Manager',
      company: 'Barnes & Noble',
      email: 'yobanny.lopez@bn.com',
      linkedinUrl: 'https://www.linkedin.com/in/yobanny-lopez-58b3114a',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Distribution Center',
      currentMandate: 'Named warehouse operations leader in Barnes & Noble network.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-070',
      name: 'Patrick Chmielowiec',
      firstName: 'Patrick',
      lastName: 'Chmielowiec',
      title: 'IT-PMO Manager, Distribution Center',
      company: 'Barnes & Noble',
      email: 'patrick.chmielowiec@bn.com',
      linkedinUrl: 'https://www.linkedin.com/in/patrickchmielowiec',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Systems / Transformation',
      currentMandate: 'Named supply-chain systems / PMO contact in B&N distribution.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'P-066',
        name: 'Annette Danek-Akey',
        firstName: 'Annette',
        lastName: 'Danek-Akey',
        title: 'Chief Supply Chain Officer',
        company: 'Barnes & Noble',
        email: 'annette.danek-akey@bn.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Supply Chain',
      },
      fallbackLane: 'ops',
      label: 'Annette Danek-Akey - Chief Supply Chain Officer',
      variantSlug: 'annette-danek-akey',

      framingNarrative: 'Annette, Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Barnes & Noble.',
      stakeStatement: 'Every minute of excess dwell time at Barnes & Noble\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Annette, the yard is where Barnes & Noble\'s execution breaks down',
        subheadline: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Annette, let\'s walk your yard network',
        subtext: '30-minute conversation about Barnes & Noble\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Annette',
        personContext: 'Named session speaker indicates event involvement.',
      },

      toneShift: 'Operator-to-operator. Annette lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Annette\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-067',
        name: 'John Huggan',
        firstName: 'John',
        lastName: 'Huggan',
        title: 'Senior Director Logistics',
        company: 'Barnes & Noble',
        email: 'john.huggan@bn.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Distribution Center Operations',
      },
      fallbackLane: 'ops',
      label: 'John Huggan - Senior Director Logistics',
      variantSlug: 'john-huggan',

      framingNarrative: 'John, Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Barnes & Noble.',
      stakeStatement: 'Every minute of excess dwell time at Barnes & Noble\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'John, the yard is where Barnes & Noble\'s execution breaks down',
        subheadline: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'John, let\'s walk your yard network',
        subtext: '30-minute conversation about Barnes & Noble\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'John',
        personContext: 'Named session speaker indicates event involvement.',
      },

      toneShift: 'Operator-to-operator. John lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with John\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-068',
        name: 'Joe Marmorato',
        firstName: 'Joe',
        lastName: 'Marmorato',
        title: 'Senior Manager, Fulfillment Operations',
        company: 'Barnes & Noble',
        email: 'joe.marmorato@bn.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Transportation / Fulfillment',
      },
      fallbackLane: 'logistics',
      label: 'Joe Marmorato - Senior Manager',
      variantSlug: 'joe-marmorato',

      framingNarrative: 'Joe, Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Barnes & Noble.',
      stakeStatement: 'Every minute of excess dwell time at Barnes & Noble\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Joe, the yard is where Barnes & Noble\'s execution breaks down',
        subheadline: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Joe, let\'s walk your yard network',
        subtext: '30-minute conversation about Barnes & Noble\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Joe',
        personContext: 'Named session speaker indicates event involvement.',
      },

      toneShift: 'Operator-to-operator. Joe lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Joe\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-069',
        name: 'Yobanny Lopez',
        firstName: 'Yobanny',
        lastName: 'Lopez',
        title: 'Senior Warehouse Operations Manager',
        company: 'Barnes & Noble',
        email: 'yobanny.lopez@bn.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Distribution Center',
      },
      fallbackLane: 'ops',
      label: 'Yobanny Lopez - Senior Warehouse Operations Manager',
      variantSlug: 'yobanny-lopez',

      framingNarrative: 'Yobanny, Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Barnes & Noble.',
      stakeStatement: 'Every minute of excess dwell time at Barnes & Noble\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Yobanny, the yard is where Barnes & Noble\'s execution breaks down',
        subheadline: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Yobanny, let\'s walk your yard network',
        subtext: '30-minute conversation about Barnes & Noble\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Yobanny',
        personContext: 'Named session speaker indicates event involvement.',
      },

      toneShift: 'Operator-to-operator. Yobanny lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'detention cost', 'throughput', 'operational efficiency'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Yobanny\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-070',
        name: 'Patrick Chmielowiec',
        firstName: 'Patrick',
        lastName: 'Chmielowiec',
        title: 'IT-PMO Manager, Distribution Center',
        company: 'Barnes & Noble',
        email: 'patrick.chmielowiec@bn.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Systems / Transformation',
      },
      fallbackLane: 'ops',
      label: 'Patrick Chmielowiec - IT-PMO Manager',
      variantSlug: 'patrick-chmielowiec',

      framingNarrative: 'Patrick, Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Barnes & Noble.',
      stakeStatement: 'Every minute of excess dwell time at Barnes & Noble\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Patrick, the yard is where Barnes & Noble\'s execution breaks down',
        subheadline: 'Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Patrick, let\'s walk your yard network',
        subtext: '30-minute conversation about Barnes & Noble\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Patrick',
        personContext: 'Named session speaker indicates event involvement.',
      },

      toneShift: 'Operator-to-operator. Patrick lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'detention cost', 'throughput', 'operational efficiency'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Patrick\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live', context: 'Measured across live deployments' },
        { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across comparable verticals' },
        { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
        { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at retail facilities' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'The yard used to be where we lost visibility. Now it is where we gain control over every trailer in the network.',
        role: 'Operations Director',
        company: 'National Retail Distributor',
      },
    },
  ],

  network: {
    facilityCount: '8',
    facilityTypes: ['Regional Distribution Centers', 'E-commerce Fulfillment Centers'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '500+ across network',
    fleet: '3PL-dependent; parcel, LTL, and truckload mix',
  },

  freight: {
    primaryModes: ['Truckload', 'LTL', 'Intermodal'],
    avgLoadsPerDay: '500+',
    peakSeason: 'Named session speaker indicates event involvement.',
  },

  signals: {
    modexAttendance: 'Named speaker',
    recentNews: [
      'Named session speaker indicates event involvement.',
    ],
    supplyChainInitiatives: ['Named speaker gives strong attendance signal; retail replenishment pain can map well to yard flow.'],
    urgencyDriver: 'Named session speaker indicates event involvement.',
  },

  theme: {
    accentColor: '#059669',
    backgroundVariant: 'dark',
  },


};
