/**
 * Constellation Brands — ABM Microsite Data
 * Quality Tier: A
 * Generated by scripts/generate-microsite-data.ts
 * 
 * Sources:
 *   - Standalone executive dossier (deep research)
 *   - Top-10 research dossier (medium research)
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (1 named contacts)
 */

import type { AccountMicrositeData } from '../schema';


// LEGACY SECTIONS (preserved for reference — M3.2-M3.6 may lift prose into memo sections)
/*
 * [
 *     {
 *       type: 'hero',
 *       headline: 'Cross-Border Receiving Chaos. That is a yard problem.',
 *       subheadline: 'The Veracruz Ramp-Up Problem (2025-2027) - As the Veracruz brewery comes online, US receiving infrastructure must absorb 30-50% more inbound volume - Kester needs to prove that existing US yard/DC infrastructure can handle the growth WITHOUT proportional CapEx increases - YardFlow\'s value prop: absorb brewery expansion volume through software, not concrete',
 *       accountCallout: 'Constellation Brands - Beverage',
 *       backgroundTheme: 'dark',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Constellation Brands',
 *         subtext: '30-minute walk-through of your facility network with board-ready ROI.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *     },
 *     {
 *       type: 'problem',
 *       sectionLabel: 'The Hidden Constraint',
 *       headline: 'The yard is where Constellation Brands\'s supply chain math breaks down',
 *       narrative: 'The Veracruz Ramp-Up Problem (2025-2027) - As the Veracruz brewery comes online, US receiving infrastructure must absorb 30-50% more inbound volume - Kester needs to prove that existing US yard/DC infrastructure can handle the growth WITHOUT proportional CapEx increases - YardFlow\'s value prop: absorb brewery expansion volume through software, not concrete',
 *       painPoints: [
 *         {
 *           headline: 'Cross-Border Receiving Chaos',
 *           description: 'Trucks crossing from Mexico arrive on border time, not appointment time — CBP delays, bridge congestion, and broker holds mean arrival windows are wide - US receiving yards must absorb unpredictable surges of inbound trailers - If dock doors are occupied and yard staging is full, trucks queu',
 *           relevantPeople: ['constellation-brands-kester'],
 *         },
 *         {
 *           headline: 'Seasonal Demand Spikes',
 *           description: '| Season | Impact | |--------|--------| | Memorial Day → Labor Day (beer) | 40-60% volume surge; Corona/Modelo peak consumption | | Cinco de Mayo (beer) | Single biggest beer sales week of the year | | Thanksgiving → New Year\'s (wine/spirits) | Wine and spirits peak; Kim Crawford, Robert',
 *           relevantPeople: ['constellation-brands-kester'],
 *         },
 *         {
 *           headline: 'Beverage Weight & Volume Challenges',
 *           description: 'Beer is heavy (~2,200 lbs per pallet of 12-packs, ~20 pallets per trailer = ~44,000 lbs) - Legal truck weight limits (80,000 lbs gross) mean beer trucks are often weight-limited before they\'re cube-limited - This means more trucks for the same volume compared to lighter goods → more ya',
 *           relevantPeople: ['constellation-brands-kester'],
 *         },
 *         {
 *           headline: 'Three-Tier Distribution Complexity',
 *           description: 'Constellation can\'t ship direct to retail — must go through licensed distributors - This means product flows: Mexico brewery → border crossing → Constellation receiving yard → Constellation DC → distributor pickup → distributor warehouse → retail - The Constellation yard is the critical hand',
 *           relevantPeople: ['constellation-brands-kester'],
 *         },
 *         {
 *           headline: 'Glass Plant Integration (Nava)',
 *           description: 'The Owens-Illinois glass plant is adjacent to the Nava brewery — producing bottles on-site - This creates bidirectional yard traffic: raw materials inbound + finished glass to brewery + finished beer outbound - Complex yard choreography with multiple trailer types and priorities -',
 *           relevantPeople: ['constellation-brands-kester'],
 *         }
 *       ],
 *     },
 *     {
 *       type: 'stakes',
 *       sectionLabel: 'What This Costs You',
 *       headline: 'The math Constellation Brands is not tracking in one place',
 *       narrative: 'Trucks crossing from Mexico arrive on border time, not appointment time — CBP delays, bridge congestion, and broker holds mean arrival windows are wide - US receiving yards must absorb unpredictable surges of inbound trailers - If dock doors are occupied and yard staging is full, trucks queu Meanwhile, | Season | Impact | |--------|--------| | Memorial Day → Labor Day (beer) | 40-60% volume surge; Corona/Modelo peak consumption | | Cinco de Mayo (beer) | Single biggest beer sales week of the year | | Thanksgiving → New Year\'s (wine/spirits) | Wine and spirits peak; Kim Crawford, Robert',
 *       annualCost: '$10M-$15M in estimated yard-driven inefficiency across the network',
 *       costBreakdown: [
 *         { label: 'Carrier detention / demurrage', value: '$4M+' },
 *         { label: 'Dock contention and turn time excess', value: '$3M+' },
 *         { label: 'Gate and spotter labor overhead', value: '$2M+' },
 *         { label: 'Peak season surge inefficiency', value: '$1M+' },
 *       ],
 *       urgencyDriver: 'Constellation Brands is investing in supply chain transformation.',
 *     },
 *     {
 *       type: 'solution',
 *       sectionLabel: 'The Fix',
 *       headline: 'One protocol across every Constellation Brands yard',
 *       narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Same driver journey at every facility. same dock assignment logic. Variance dies. Throughput becomes calculable.',
 *       modules: [
 *         { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Standardizes verify across Constellation Brands\'s facility network.' },
 *         { id: 'flowBOL', name: 'flowBOL', verb: 'Document', shortDescription: 'Touchless BOL creation with timestamped chain of custody.', relevanceToAccount: 'Standardizes document across Constellation Brands\'s facility network.' },
 *         { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. No more radio dispatching.', relevanceToAccount: 'Standardizes execute across Constellation Brands\'s facility network.' },
 *         { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Standardizes map across Constellation Brands\'s facility network.' },
 *       ],
 *       accountFit: '1. **The Veracruz Ramp-Up Problem (2025-2027)**    - As the Veracruz brewery comes online, US receiving infrastructure must absorb 30-50% more inbound volume    - Kester needs to prove that existing US yard/DC infrastructure can handle the growth WITHOUT proportional CapEx increases    - YardFlow\'s value prop: **absorb brewery expansion volume through software, not concrete**',
 *     },
 *     {
 *       type: 'proof',
 *       sectionLabel: 'Proof from Live Deployment',
 *       headline: 'Running today across 24 facilities',
 *       blocks: [
 *         {
 *           type: 'metric',
 *           stats: [
 *             { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol at comparable beverage operations' },
 *             { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across similar verticals' },
 *             { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
 *             { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at beverage facilities' },
 *           ],
 *         },
 *         {
 *           type: 'quote',
 *           quote: {
 *             text: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office. That was an integral part of our strategy and has been proven.',
 *             role: 'Operations Director',
 *             company: 'National CPG/Beverage Manufacturer',
 *           },
 *         },
 *       ],
 *     },
 *     {
 *       type: 'network-map',
 *       sectionLabel: 'Your Network',
 *       headline: 'Constellation Brands\'s yard network at scale',
 *       narrative: 'Every one of these facilities runs its own yard protocol today. Different gate processes, different spotter dispatch methods, different tribal knowledge. YardFlow gives you one standard across all of them.',
 *       facilityCount: '20+',
 *       facilityTypes: ['Manufacturing Plants', 'Distribution Centers'],
 *       geographicSpread: 'North America',
 *       dailyTrailerMoves: '1,000+ across the network',
 *     },
 *     {
 *       type: 'roi',
 *       sectionLabel: 'The Business Case',
 *       headline: 'Conservative ROI model for Constellation Brands',
 *       narrative: 'Based on measured YardFlow improvements at comparable operations.',
 *       roiLines: [
 *         { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
 *         { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
 *         { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
 *         { label: 'Dock utilization', before: '65%', after: '85%', delta: '+20 pts', unit: 'utilization' },
 *       ],
 *       totalAnnualSavings: '$10M-$15M across the network',
 *       paybackPeriod: '< 6 months',
 *       methodology: 'Based on measured results at 24 live facilities extrapolated to Constellation Brands facility count and operational profile.',
 *     },
 *     {
 *       type: 'testimonial',
 *       sectionLabel: 'From an Operator Who Runs It',
 *       quote: 'We believe system-driven dock door assignment will be a valuable next step for dock office optimization.',
 *       role: 'Operations Director',
 *       company: 'National CPG/Beverage Manufacturer',
 *       context: 'After 12 months of full YardFlow deployment across their facility network.',
 *     },
 *     {
 *       type: 'cta',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Constellation Brands',
 *         subtext: 'We map your top 3 facilities, identify the throughput constraint, and build a board-ready rollout plan.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *       closingLine: 'One conversation. Your yard network. A clear path to $10M-$15M in annual savings.',
 *     },
 *   ]
 */

export const constellationBrands: AccountMicrositeData = {
  slug: 'constellation-brands',
  accountName: 'Constellation Brands',
  vertical: 'beverage',
  tier: 'Tier 2',
  band: 'B',
  priorityScore: 75,

  pageTitle: "Constellation Brands · Wine, beer, spirits — three temperature regimes, one yard",
  metaDescription: "Constellation Brands moves Corona, Modelo, and the Robert Mondavi portfolio through a yard layer that handles three temperature regimes and three regulatory contexts simultaneously. Single-brand WMS doesn't model that constraint.",

  sections: [],

  people: [
    {
      personaId: 'constellation-brands-001',
      name: 'John Kester',
      firstName: 'John',
      lastName: 'Kester',
      title: 'SVP & Chief Supply Chain Officer, Constellation Brands',
      company: 'Constellation Brands',
      email: 'john.kester@cbrands.com',
      roleInDeal: 'decision-maker',
      seniority: 'C-level',
      function: 'Supply Chain / Operations',
      currentMandate: '### Title & Role\n- **SVP and Chief Supply Chain Officer** at Constellation Brands (NYSE: STZ)\n- Owns end-to-end supply chain for the **#1 beer import company in the US** and a major wine & spirits portfolio\n- Reports to CEO Bill Newlands; sits on the executive leadership team\n- Responsible for brewery operations in Mexico, wine/spirits production in US/NZ/Italy, cross-border logistics, and US distribution infrastructure\n\n### Career Context\n- The CSCO role at Constellation is relatively new at th',
      knownForPhrase: '### Title & Role\n- **SVP and Chief Supply Chain Officer** at Constellation Brands (NYSE: STZ)\n- Owns end-to-end supply chain for the **#1 beer import company in the US** and a major wine & spirits por',
      bestIntroPath: 'Direct outreach',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'constellation-brands-001',
        name: 'John Kester',
        firstName: 'John',
        lastName: 'Kester',
        title: 'SVP & Chief Supply Chain Officer, Constellation Brands',
        company: 'Constellation Brands',
        email: 'john.kester@cbrands.com',
        roleInDeal: 'decision-maker',
        seniority: 'C-level',
        function: 'Supply Chain / Operations',
      },
      fallbackLane: 'ops',
      label: 'John Kester - SVP & Chief Supply Chain Officer',
      variantSlug: 'john-kester',

      framingNarrative: 'John, 1. **The Veracruz Ramp-Up Problem (2025-2027)**    - As the Veracruz brewery comes online, US receiving infrastructure must absorb 30-50% more inbound volume    - Kester needs to prove that existing US yard/DC infrastructure can handle the growth WITHOUT proportional CapEx increases    - YardFlow\'s value prop: **absorb brewery expansion volume through software, not concrete**',
      openingHook: 'Your team is dealing with 4a. cross-border receiving chaos. That is a yard problem before it is anything else.',
      stakeStatement: '| Season | Impact | |--------|--------| | **Memorial Day → Labor Day** (beer) | 40-60% volume surge; Corona/Modelo peak consumption | | **Cinco de Mayo** (beer) | Single biggest beer sales week of the year | | **Thanksgiving → New Year\'s** (wine/spirits) | Wine and spirits peak; Kim Crawford, Robert',

      heroOverride: {
        headline: 'John, the yard is where Constellation Brands\'s execution breaks down',
        subheadline: '1. **The Veracruz Ramp-Up Problem (2025-2027)**    - As the Veracruz brewery comes online, US receiving infrastructure must absorb 30-50% more inbound volume    - Kester needs to prove that existing US yard/DC infrastructure can handle the growth WITHOUT proportional CapEx increases    - YardFlow\'s value prop: **absorb brewery expansion volume through software, not concrete**',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],

      toneShift: 'Strategic, board-level. Reference John\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with John\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live', context: 'Measured at comparable beverage operations' },
        { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across comparable verticals' },
        { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
        { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at beverage facilities' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office.',
        role: 'Operations Director',
        company: 'National CPG/Beverage Manufacturer',
      },
    },
  ],

  network: {
    facilityCount: '20+',
    facilityTypes: ['Manufacturing Plants', 'Distribution Centers'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '1,000+ across network',
    fleet: 'Contract carriers and 3PL',
  },

  freight: {
    primaryModes: ['Truckload', 'Intermodal/Rail', 'LTL'],
    avgLoadsPerDay: '1,000+',
    peakSeason: 'Constellation Brands is investing in supply chain transformation.',
  },

  signals: {
    eventAttendance: 'Industry conference attendee signal',
    recentNews: [
      'Constellation Brands is investing in supply chain transformation.',
    ],
    supplyChainInitiatives: ['1. **The Veracruz Ramp-Up Problem (2025-2027)**    - As the Veracruz brewery comes online, US receiving infrastructure must absorb 30-50% more inbound volume    - Kester needs to prove that existing US yard/DC infrastructure can handle the growth WITHOUT proportional CapEx increases    - YardFlow\'s value prop: **absorb brewery expansion volume through software, not concrete**'],
    urgencyDriver: 'Constellation Brands is investing in supply chain transformation.',
  },

  theme: {
    accentColor: '#7C3AED',
    backgroundVariant: 'dark',
  },


};
