/**
 * Dannon (Danone North America) — ABM Microsite Data
 * Quality Tier: B
 * WARM INTRO ONLY — via Mark Shaughnessy
 * NEVER cold email or cold outreach
 * 
 * Generated by scripts/generate-microsite-data.ts
 * Sources:
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (5 named contacts)
 */

import type { AccountMicrositeData } from '../schema';

const BOOKING_LINK = 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2UyZRVDBYFwV3QOTx7-WK4APujmADpAGspAqeR5qAmK4KJjN2P1QNIrsVj0SPO0qMZIWKzuPoW';

export const dannon: AccountMicrositeData = {
  slug: 'dannon',
  accountName: 'Dannon',
  parentBrand: 'Danone North America',
  vertical: 'cpg',
  tier: 'Tier 1',
  band: 'A',
  priorityScore: 95,

  pageTitle: 'YardFlow for Danone North America - Yard Network Standardization',
  metaDescription: 'How YardFlow eliminates the yard bottleneck across Danone North America\'s production and distribution network.',

  sections: [
    {
      type: 'hero',
      headline: 'Fresh dairy has a 14-day shelf clock. Every hour your trailers wait in the yard is product life you never get back.',
      subheadline: 'Danone runs 15+ North American production facilities across dairy, plant-based, medical nutrition, and water. Four temperature profiles competing for dock doors at every multi-category facility. YardFlow standardizes the yard across all of them.',
      accountCallout: 'Danone North America - Fresh Dairy, Plant-Based, Medical Nutrition, Waters',
      backgroundTheme: 'dark',
      cta: {
        type: 'meeting',
        headline: 'See what a standardized yard looks like for Danone',
        subtext: '30-minute walk-through of your facility network with board-ready ROI. Routed through Mark Shaughnessy.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
      },
    },
    {
      type: 'problem',
      sectionLabel: 'The Hidden Constraint',
      headline: 'The yard is where Danone\'s product freshness commitment breaks down',
      narrative: 'Danone North America produces fresh dairy, plant-based products, and medical nutrition - all with tight shelf life windows. When a refrigerated trailer sits an extra 30 minutes in the yard during summer, product quality degrades. The yard is not just a logistics problem. It is a quality problem.',
      painPoints: [
        {
          headline: 'Temperature-controlled yard dwell erodes shelf life',
          description: 'Danone moves fresh and chilled dairy products across 15+ plants. Reefer trailers sitting in yards without visibility into dock readiness means product shelf life burns before the case is even picked. At dairy margins, that dwell is measurable in shrink dollars.',
          kpiImpact: '$3M-$5M in annual shrink exposure from excess yard dwell across the fresh network',
          relevantPeople: ['P-001', 'P-002'],
        },
        {
          headline: 'Plant-level yard protocols fragment cross-facility visibility',
          description: 'Each Danone production facility runs its own gate, dock, and spotter coordination. When the White Plains supply chain team wants a network view of trailer utilization or dock throughput, they are stitching together spreadsheets from 15 different local teams.',
          kpiImpact: 'Zero real-time network visibility across the yard layer',
          relevantPeople: ['P-001', 'P-003'],
        },
        {
          headline: 'Carrier detention costs compound across the fresh network',
          description: 'Fresh dairy carriers operate on tight appointment windows. When dock contention pushes wait times past the threshold, detention charges hit every facility individually. No one is tracking the aggregate network-level carrier cost.',
          kpiImpact: '$2M+ in annual detention and accessorial charges across the network',
          relevantPeople: ['P-002', 'P-004'],
        },
      ],
    },
    {
      type: 'stakes',
      sectionLabel: 'What This Costs You',
      headline: 'The freshness math Danone is not tracking in one place',
      narrative: 'Every minute of excess yard dwell time at a Danone facility is a minute off product shelf life. Across 15+ facilities producing perishable goods, that time compounds into quality events, carrier dissatisfaction, and hidden costs distributed across dozens of GL codes.',
      annualCost: '$5M-$8M in estimated yard-driven inefficiency across the North America network',
      costBreakdown: [
        { label: 'Product shrink from yard dwell on perishables', value: '$3M-$5M' },
        { label: 'Carrier detention / demurrage across fresh network', value: '$2M+' },
        { label: 'Gate and spotter labor overhead (15+ facilities)', value: '$1M+' },
        { label: 'Temperature-zone dock misassignment events', value: '$500K+' },
      ],
      urgencyDriver: 'Fresh dairy and plant-based products have zero tolerance for yard-induced delays. Every season compounds the problem.',
    },
    {
      type: 'solution',
      sectionLabel: 'The Fix',
      headline: 'One protocol across every Danone yard',
      narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Temperature-zone dock assignment enforced automatically. Freshness-critical loads prioritized. Same driver journey at every facility.',
      modules: [
        { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Standardizes the gate process across 15+ Danone facilities.' },
        { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. Temperature-zone aware.', relevanceToAccount: 'Enforces temp-zone dock assignment. Fresh dairy goes to refrigerated. Every time.' },
        { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Visibility into dwell time for perishable loads. Freshness clock starts in the yard.' },
        { id: 'flowNETWORK', name: 'flowNETWORK', verb: 'Scale', shortDescription: 'Network-wide command view with alerting and cross-site performance intelligence.', relevanceToAccount: 'One view across all Danone North America yard operations.' },
      ],
      accountFit: 'Primo proof should land hardest here because both are high-volume food / beverage-style networks with plant throughput pressure.',
    },
    {
      type: 'proof',
      sectionLabel: 'Proof from Live Deployment',
      headline: 'Running today across 24 facilities',
      blocks: [
        {
          type: 'metric',
          stats: [
            { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol today' },
            { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout' },
            { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
            { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured across live deployments' },
          ],
        },
        {
          type: 'quote',
          quote: {
            text: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office.',
            role: 'Operations Director',
            company: 'National CPG/Beverage Manufacturer',
          },
        },
      ],
    },
    {
      type: 'network-map',
      sectionLabel: 'Your Network',
      headline: 'Danone North America\'s yard network',
      narrative: 'Every facility runs its own yard protocol today. YardFlow gives Danone one standard across all of them - with temperature-zone intelligence built in.',
      facilityCount: '15+',
      facilityTypes: ['Dairy Production', 'Plant-Based Production', 'Water Operations', 'Distribution Centers'],
      geographicSpread: 'North America',
      dailyTrailerMoves: '1,000+ across the network',
    },
    {
      type: 'roi',
      sectionLabel: 'The Business Case',
      headline: 'Conservative ROI model for Danone North America',
      narrative: 'Based on measured YardFlow improvements at comparable fresh food/beverage operations.',
      roiLines: [
        { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
        { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
        { label: 'Temp-zone dock errors', before: '3-5/week', after: '<1/week', delta: '-80%', unit: 'per facility' },
        { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
      ],
      totalAnnualSavings: '$5M-$8M across the network',
      paybackPeriod: '< 6 months',
      methodology: 'Based on measured results at 24 live CPG facilities extrapolated to Danone facility count and operational profile.',
    },
    {
      type: 'testimonial',
      sectionLabel: 'From an Operator Who Runs It',
      quote: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office.',
      role: 'Operations Director',
      company: 'National CPG/Beverage Manufacturer',
      context: 'After 12 months of full YardFlow deployment across their facility network.',
    },
    {
      type: 'cta',
      cta: {
        type: 'meeting',
        headline: 'Danone is a warm introduction through Mark Shaughnessy',
        subtext: 'This conversation is routed through a trusted mutual connection. 30 minutes to walk your yard network.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
      },
      closingLine: 'One conversation. Your yard network. A clear path to $5M+ in annual freshness-protected savings.',
    },
  ],

  people: [
    {
      personaId: 'P-001',
      name: 'Heiko Gerling',
      firstName: 'Heiko',
      lastName: 'Gerling',
      title: 'Chief Operations Officer, North America',
      company: 'Dannon',
      email: 'heiko.gerling@danone.com',
      linkedinUrl: 'https://www.danonenorthamerica.com/about-us/our-leaders.html',
      roleInDeal: 'decision-maker',
      seniority: 'C-level',
      function: 'Operations / Supply Chain',
      currentMandate: 'Official Danone North America operations lead spanning manufacturing, logistics, customer service, procurement, and S&OP.',
      bestIntroPath: 'Mark -> Heiko / CSCO office',
    },
    {
      personaId: 'P-002',
      name: 'Whitney Klemm',
      firstName: 'Whitney',
      lastName: 'Klemm',
      title: 'Supply Chain Leader',
      company: 'Dannon',
      email: 'whitney.klemm@danone.com',
      linkedinUrl: 'https://www.linkedin.com/in/whitneyklemm',
      roleInDeal: 'routing-contact',
      seniority: 'C-level',
      function: 'Supply Chain',
      currentMandate: 'Relevant Danone supply chain operator who can help triangulate the North America org.',
      bestIntroPath: 'Use intro to request proper routing if Heiko delegates',
    },
    {
      personaId: 'P-003',
      name: 'Jacqueline Beckman',
      firstName: 'Jacqueline',
      lastName: 'Beckman',
      title: 'Senior Procurement Manager',
      company: 'Dannon',
      email: 'jacqueline.beckman@danone.com',
      linkedinUrl: 'https://www.linkedin.com/in/jacqueline-vesey',
      roleInDeal: 'influencer',
      seniority: 'VP',
      function: 'Procurement / Logistics',
      currentMandate: 'Procurement and supplier-side operator tied to the Danone network.',
      bestIntroPath: 'LinkedIn / network outreach',
    },
    {
      personaId: 'P-004',
      name: 'Annette Tolve',
      firstName: 'Annette',
      lastName: 'Tolve',
      title: 'Demand Planner',
      company: 'Dannon',
      email: 'annette.tolve@danone.com',
      linkedinUrl: 'https://www.linkedin.com/in/annette-tolve-40687b98',
      roleInDeal: 'influencer',
      seniority: 'VP',
      function: 'Planning / Customer Operations',
      currentMandate: 'Planning contact useful for S&OP and service-level angle.',
      bestIntroPath: 'LinkedIn / network outreach',
    },
    {
      personaId: 'P-005',
      name: 'Jay Luikart',
      firstName: 'Jay',
      lastName: 'Luikart',
      title: 'Operations Executive, Away From Home',
      company: 'Dannon',
      email: 'jay.luikart@danone.com',
      linkedinUrl: 'https://www.linkedin.com/in/jayluikart',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Plant / Site Operations',
      currentMandate: 'Public profile references Danone North America scope including manufacturing, logistics, warehousing, procurement, and S&OP.',
      bestIntroPath: 'LinkedIn / network outreach',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'P-001',
        name: 'Heiko Gerling',
        firstName: 'Heiko',
        lastName: 'Gerling',
        title: 'Chief Operations Officer, North America',
        company: 'Dannon',
        email: 'heiko.gerling@danone.com',
        roleInDeal: 'decision-maker',
        seniority: 'C-level',
        function: 'Operations / Supply Chain',
      },
      fallbackLane: 'ops',
      label: 'Heiko Gerling - Chief Operations Officer',
      variantSlug: 'heiko-gerling',

      framingNarrative: 'Heiko, When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      openingHook: 'Warm intro via Mark Shaughnessy and likely MODEX attendance - the yard is where execution meets reality for Dannon.',
      stakeStatement: 'Every minute of excess dwell time at Dannon\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Heiko, 15 facilities. Four temperature profiles. One yard protocol. That is the standard Danone North America needs.',
        subheadline: 'When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'warm-intro',
        headline: 'Heiko, this conversation is routed through Mark Shaughnessy',
        subtext: 'A trusted mutual connection. 30 minutes to walk Danone\'s yard network with Casey.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
        personName: 'Heiko',
        personContext: 'Warm intro via Mark Shaughnessy',
      },

      toneShift: 'Strategic, board-level. Reference Heiko\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Heiko\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-002',
        name: 'Whitney Klemm',
        firstName: 'Whitney',
        lastName: 'Klemm',
        title: 'Supply Chain Leader',
        company: 'Dannon',
        email: 'whitney.klemm@danone.com',
        roleInDeal: 'routing-contact',
        seniority: 'C-level',
        function: 'Supply Chain',
      },
      fallbackLane: 'ops',
      label: 'Whitney Klemm - Supply Chain Leader',
      variantSlug: 'whitney-klemm',

      framingNarrative: 'Whitney, When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      openingHook: 'Warm intro via Mark Shaughnessy and likely MODEX attendance - the yard is where execution meets reality for Dannon.',
      stakeStatement: 'Every minute of excess dwell time at Dannon\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Whitney, the supply chain team sees network metrics. The yard is the layer where those metrics break.',
        subheadline: 'When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'warm-intro',
        headline: 'Whitney, this conversation is routed through Mark Shaughnessy',
        subtext: 'A trusted mutual connection. 30 minutes to walk Danone\'s yard network with Casey.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
        personName: 'Whitney',
        personContext: 'Warm intro via Mark Shaughnessy',
      },

      toneShift: 'Strategic, board-level. Reference Whitney\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Whitney\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-003',
        name: 'Jacqueline Beckman',
        firstName: 'Jacqueline',
        lastName: 'Beckman',
        title: 'Senior Procurement Manager',
        company: 'Dannon',
        email: 'jacqueline.beckman@danone.com',
        roleInDeal: 'influencer',
        seniority: 'VP',
        function: 'Procurement / Logistics',
      },
      fallbackLane: 'logistics',
      label: 'Jacqueline Beckman - Senior Procurement Manager',
      variantSlug: 'jacqueline-beckman',

      framingNarrative: 'Jacqueline, When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      openingHook: 'Warm intro via Mark Shaughnessy and likely MODEX attendance - the yard is where execution meets reality for Dannon.',
      stakeStatement: 'Every minute of excess dwell time at Dannon\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Jacqueline, every carrier detention charge at a Danone plant is a procurement problem hiding in the yard.',
        subheadline: 'When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'warm-intro',
        headline: 'Jacqueline, this conversation is routed through Mark Shaughnessy',
        subtext: 'A trusted mutual connection. 30 minutes to walk Danone\'s yard network with Casey.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
        personName: 'Jacqueline',
        personContext: 'Warm intro via Mark Shaughnessy',
      },

      toneShift: 'Operator-to-operator. Jacqueline lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Jacqueline\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-004',
        name: 'Annette Tolve',
        firstName: 'Annette',
        lastName: 'Tolve',
        title: 'Demand Planner',
        company: 'Dannon',
        email: 'annette.tolve@danone.com',
        roleInDeal: 'influencer',
        seniority: 'VP',
        function: 'Planning / Customer Operations',
      },
      fallbackLane: 'ops',
      label: 'Annette Tolve - Demand Planner',
      variantSlug: 'annette-tolve',

      framingNarrative: 'Annette, When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      openingHook: 'Warm intro via Mark Shaughnessy and likely MODEX attendance - the yard is where execution meets reality for Dannon.',
      stakeStatement: 'Every minute of excess dwell time at Dannon\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Annette, the demand plan is only as good as the dock execution that fulfills it. The yard is the gap.',
        subheadline: 'When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'warm-intro',
        headline: 'Annette, this conversation is routed through Mark Shaughnessy',
        subtext: 'A trusted mutual connection. 30 minutes to walk Danone\'s yard network with Casey.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
        personName: 'Annette',
        personContext: 'Warm intro via Mark Shaughnessy',
      },

      toneShift: 'Operator-to-operator. Annette lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Annette\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-005',
        name: 'Jay Luikart',
        firstName: 'Jay',
        lastName: 'Luikart',
        title: 'Operations Executive, Away From Home',
        company: 'Dannon',
        email: 'jay.luikart@danone.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Plant / Site Operations',
      },
      fallbackLane: 'it',
      label: 'Jay Luikart - Operations Executive',
      variantSlug: 'jay-luikart',

      framingNarrative: 'Jay, When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      openingHook: 'Warm intro via Mark Shaughnessy and likely MODEX attendance - the yard is where execution meets reality for Dannon.',
      stakeStatement: 'Every minute of excess dwell time at Dannon\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Jay, the Away From Home network runs on tight appointments. The yard is where appointment precision dies.',
        subheadline: 'When the cold chain breaks in the yard, Danone does not lose product. It loses shelf days.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'warm-intro',
        headline: 'Jay, this conversation is routed through Mark Shaughnessy',
        subtext: 'A trusted mutual connection. 30 minutes to walk Danone\'s yard network with Casey.',
        buttonLabel: 'Request an Introduction',
        calendarLink: BOOKING_LINK,
        personName: 'Jay',
        personContext: 'Warm intro via Mark Shaughnessy',
      },

      toneShift: 'Operator-to-operator. Jay lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Jay\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live' },
        { value: '>200', label: 'Contracted Network' },
        { value: '48-to-24', label: 'Min Truck Turn Time' },
        { value: '$1M+', label: 'Per-Site Profit Impact' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office.',
        role: 'Operations Director',
        company: 'National CPG/Beverage Manufacturer',
      },
    },
  ],

  network: {
    facilityCount: '15+',
    facilityTypes: ['Dairy Production', 'Plant-Based Production', 'Water Operations', 'Distribution Centers'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '1,000+ across network',
    fleet: 'Contract carriers and 3PL',
  },

  freight: {
    primaryModes: ['Truckload', 'Refrigerated', 'LTL'],
    avgLoadsPerDay: '1,000+',
    peakSeason: 'Year-round fresh dairy production',
    specialRequirements: ['Temperature-controlled (multiple zones)', 'Fresh product shelf life sensitivity'],
  },

  signals: {
    modexAttendance: 'Past attendee list signal',
    recentNews: [
      'Active Shaughnessy intro path and likely MODEX attendance signal',
    ],
    supplyChainInitiatives: ['Primo proof should land hardest here - high-volume food/beverage network with plant throughput pressure'],
    urgencyDriver: 'Active Shaughnessy intro path and likely MODEX attendance signal.',
  },

  theme: {
    accentColor: '#059669',
    backgroundVariant: 'dark',
  },

  showcase: true,
  showcaseOrder: 1,
  layoutPreset: 'partnership',
};
