/**
 * Diageo — ABM Microsite Data
 * Quality Tier: B
 * Generated by scripts/generate-microsite-data.ts
 * 
 * Sources:
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (5 named contacts)
 */

import type { AccountMicrositeData } from '../schema';

const BOOKING_LINK = 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2UyZRVDBYFwV3QOTx7-WK4APujmADpAGspAqeR5qAmK4KJjN2P1QNIrsVj0SPO0qMZIWKzuPoW';

// LEGACY SECTIONS (preserved for reference — M3.2-M3.6 may lift prose into memo sections)
/*
 * [
 *     {
 *       type: 'hero',
 *       headline: 'Diageo ages whiskey for 12 years, then loses 90 minutes at the dock door. The yard is your shortest aging process.',
 *       subheadline: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
 *       accountCallout: 'Diageo - Food & Beverage',
 *       backgroundTheme: 'dark',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Diageo',
 *         subtext: '30-minute walk-through of your facility network with board-ready ROI.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *     },
 *     {
 *       type: 'problem',
 *       sectionLabel: 'The Hidden Constraint',
 *       headline: 'Diageo ships premium product through yards that run the same way they did a decade ago.',
 *       narrative: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
 *       painPoints: [
 *         {
 *           headline: 'High-value spirits shipments sit in untracked yard queues',
 *           description: 'A trailer of Johnnie Walker or Don Julio can hold $500K+ in product. When that trailer sits in a yard queue with no priority flagging or dock assignment logic, you are parking half a million dollars in the dark.',
 *           kpiImpact: 'Working capital velocity: $500K+ per trailer sitting in yard without dock assignment',
 *           relevantPeople: ['diageo-mcintosh-hamilton', 'diageo-reddrick'],
 *         },
 *         {
 *           headline: 'Seasonal demand spikes overwhelm manual yard processes',
 *           description: 'Holiday season drives 3x throughput at Diageo distribution centers. The yard processes that work at baseline volume collapse under peak load. Gate queues back up, spotters are dispatched by phone calls, and dock turns drop below target.',
 *           kpiImpact: '15-20% throughput loss during peak season from yard bottleneck',
 *           relevantPeople: ['diageo-mcintosh-hamilton', 'diageo-reddrick'],
 *         },
 *         {
 *           headline: 'Multi-facility compliance and chain-of-custody gaps',
 *           description: 'Spirits distribution requires chain-of-custody documentation at every transfer point. Manual yard check-in processes create compliance gaps that the audit team catches months later.',
 *           kpiImpact: 'Regulatory exposure across 30+ facilities',
 *           relevantPeople: ['diageo-mcintosh-hamilton', 'diageo-reddrick'],
 *         }
 *       ],
 *     },
 *     {
 *       type: 'stakes',
 *       sectionLabel: 'What This Costs You',
 *       headline: 'The math Diageo is not tracking in one place',
 *       narrative: 'A trailer of Johnnie Walker or Don Julio can hold $500K+ in product. When that trailer sits in a yard queue with no priority flagging or dock assignment logic, you are parking half a million dollars in the dark. Meanwhile, holiday season drives 3x throughput at Diageo distribution centers. The yard processes that work at baseline volume collapse under peak load. Gate queues back up, spotters are dispatched by phone calls, and dock turns drop below target.',
 *       annualCost: '$10M-$15M in estimated yard-driven inefficiency across the network',
 *       costBreakdown: [
 *         { label: 'Carrier detention / demurrage', value: '$4M+' },
 *         { label: 'Dock contention and turn time excess', value: '$3M+' },
 *         { label: 'Gate and spotter labor overhead', value: '$2M+' },
 *         { label: 'Peak season surge inefficiency', value: '$1M+' },
 *       ],
 *       urgencyDriver: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
 *     },
 *     {
 *       type: 'solution',
 *       sectionLabel: 'The Fix',
 *       headline: 'One protocol across every Diageo yard',
 *       narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Same driver journey at every facility. same dock assignment logic. Variance dies. Throughput becomes calculable.',
 *       modules: [
 *         { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Standardizes verify across Diageo\'s facility network.' },
 *         { id: 'flowBOL', name: 'flowBOL', verb: 'Document', shortDescription: 'Touchless BOL creation with timestamped chain of custody.', relevanceToAccount: 'Standardizes document across Diageo\'s facility network.' },
 *         { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. No more radio dispatching.', relevanceToAccount: 'Standardizes execute across Diageo\'s facility network.' },
 *         { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Standardizes map across Diageo\'s facility network.' },
 *       ],
 *       accountFit: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
 *     },
 *     {
 *       type: 'proof',
 *       sectionLabel: 'Proof from Live Deployment',
 *       headline: 'Running today across 24 facilities',
 *       blocks: [
 *         {
 *           type: 'metric',
 *           stats: [
 *             { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol at comparable food & beverage operations' },
 *             { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across similar verticals' },
 *             { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
 *             { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at food & beverage facilities' },
 *           ],
 *         },
 *         {
 *           type: 'quote',
 *           quote: {
 *             text: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office. That was an integral part of our strategy and has been proven.',
 *             role: 'Operations Director',
 *             company: 'National CPG/Beverage Manufacturer',
 *           },
 *         },
 *       ],
 *     },
 *     {
 *       type: 'network-map',
 *       sectionLabel: 'Your Network',
 *       headline: 'Diageo\'s yard network at scale',
 *       narrative: 'Every one of these facilities runs its own yard protocol today. Different gate processes, different spotter dispatch methods, different tribal knowledge. YardFlow gives you one standard across all of them.',
 *       facilityCount: '30+',
 *       facilityTypes: ['Distilleries', 'Bottling Plants', 'Aging Warehouses', 'Distribution Centers'],
 *       geographicSpread: 'North America',
 *       dailyTrailerMoves: '1,500+ across the network',
 *     },
 *     {
 *       type: 'roi',
 *       sectionLabel: 'The Business Case',
 *       headline: 'Conservative ROI model for Diageo',
 *       narrative: 'Based on measured YardFlow improvements at comparable operations.',
 *       roiLines: [
 *         { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
 *         { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
 *         { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
 *         { label: 'Dock utilization', before: '65%', after: '85%', delta: '+20 pts', unit: 'utilization' },
 *       ],
 *       totalAnnualSavings: '$10M-$15M across the network',
 *       paybackPeriod: '< 6 months',
 *       methodology: 'Based on measured results at 24 live facilities extrapolated to Diageo facility count and operational profile.',
 *     },
 *     {
 *       type: 'testimonial',
 *       sectionLabel: 'From an Operator Who Runs It',
 *       quote: 'We believe system-driven dock door assignment will be a valuable next step for dock office optimization.',
 *       role: 'Operations Director',
 *       company: 'National CPG/Beverage Manufacturer',
 *       context: 'After 12 months of full YardFlow deployment across their facility network.',
 *     },
 *     {
 *       type: 'cta',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Diageo',
 *         subtext: 'We map your top 3 facilities, identify the throughput constraint, and build a board-ready rollout plan.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *       closingLine: 'One conversation. Your yard network. A clear path to $10M-$15M in annual savings.',
 *     },
 *   ]
 */

export const diageo: AccountMicrositeData = {
  slug: 'diageo',
  accountName: 'Diageo',
  parentBrand: 'Diageo',
  vertical: 'cpg',
  tier: 'Tier 2',
  band: 'B',
  priorityScore: 83,

  pageTitle: 'YardFlow for Diageo - Yard Network Standardization',
  metaDescription: 'How YardFlow eliminates the yard bottleneck across Diageo\'s facility network.',

  sections: [],

  people: [
    {
      personaId: 'P-016',
      name: 'Marsha McIntosh-Hamilton',
      firstName: 'Marsha',
      lastName: 'McIntosh-Hamilton',
      title: 'President of North America Supply',
      company: 'Diageo',
      email: 'marsha.mcintosh-hamilton@diageo.com',
      linkedinUrl: 'https://www.diageo.com/en/our-business/where-we-operate/north-america/diageo-north-america-executive-team/marsha-mcintosh-hamilton',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Supply Chain',
      currentMandate: 'Official Diageo North America supply leader.',
      bestIntroPath: 'Direct outreach to NA supply org',
    },
    {
      personaId: 'P-017',
      name: 'Raymond Reddrick',
      firstName: 'Raymond',
      lastName: 'Reddrick',
      title: 'SVP North America Supply - Manufacturing and Distillation',
      company: 'Diageo',
      email: 'raymond.reddrick@diageo.com',
      linkedinUrl: 'https://www.linkedin.com/in/raymond-reddrick-48b63619a',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Logistics / Supply',
      currentMandate: 'Strong senior North America supply and manufacturing signal.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-018',
      name: 'Joseph Wanshek',
      firstName: 'Joseph',
      lastName: 'Wanshek',
      title: 'Procurement Director, North America Packaging',
      company: 'Diageo',
      email: 'joseph.wanshek@diageo.com',
      linkedinUrl: 'https://www.linkedin.com/in/joseph-wanshek-9b30a613',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Manufacturing / Procurement',
      currentMandate: 'North America packaging procurement leader who can route into supply/manufacturing decision-makers.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-019',
      name: 'Jose Martins',
      firstName: 'Jose',
      lastName: 'Martins',
      title: 'Category Director, Logistics North America',
      company: 'Diageo',
      email: 'jose.martins@diageo.com',
      linkedinUrl: 'https://www.linkedin.com/in/jose-martins-00834231',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Distribution / Logistics',
      currentMandate: 'Direct logistics-category signal for North America.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-020',
      name: 'Joshua Sallee',
      firstName: 'Joshua',
      lastName: 'Sallee',
      title: 'Procurement Category Manager',
      company: 'Diageo',
      email: 'joshua.sallee@diageo.com',
      linkedinUrl: 'https://www.linkedin.com/in/joshuasalleescm',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Transportation Procurement',
      currentMandate: 'Public profile references managing North America supply-chain operations with broad vendor network.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'P-016',
        name: 'Marsha McIntosh-Hamilton',
        firstName: 'Marsha',
        lastName: 'McIntosh-Hamilton',
        title: 'President of North America Supply',
        company: 'Diageo',
        email: 'marsha.mcintosh-hamilton@diageo.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Supply Chain',
      },
      fallbackLane: 'ops',
      label: 'Marsha McIntosh-Hamilton - President of North America Supply',
      variantSlug: 'marsha-mcintosh-hamilton',

      framingNarrative: 'Marsha, Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for Diageo.',
      stakeStatement: 'Every minute of excess dwell time at Diageo\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Marsha, the yard is where Diageo\'s execution breaks down',
        subheadline: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Marsha, let\'s walk your yard network',
        subtext: '30-minute conversation about Diageo\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Marsha',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Marsha lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Marsha\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-017',
        name: 'Raymond Reddrick',
        firstName: 'Raymond',
        lastName: 'Reddrick',
        title: 'SVP North America Supply - Manufacturing and Distillation',
        company: 'Diageo',
        email: 'raymond.reddrick@diageo.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Logistics / Supply',
      },
      fallbackLane: 'logistics',
      label: 'Raymond Reddrick - SVP North America Supply - Manufacturing and Distillation',
      variantSlug: 'raymond-reddrick',

      framingNarrative: 'Raymond, Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for Diageo.',
      stakeStatement: 'Every minute of excess dwell time at Diageo\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Raymond, the yard is where Diageo\'s execution breaks down',
        subheadline: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Raymond, let\'s walk your yard network',
        subtext: '30-minute conversation about Diageo\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Raymond',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Raymond lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Raymond\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-018',
        name: 'Joseph Wanshek',
        firstName: 'Joseph',
        lastName: 'Wanshek',
        title: 'Procurement Director, North America Packaging',
        company: 'Diageo',
        email: 'joseph.wanshek@diageo.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Manufacturing / Procurement',
      },
      fallbackLane: 'ops',
      label: 'Joseph Wanshek - Procurement Director',
      variantSlug: 'joseph-wanshek',

      framingNarrative: 'Joseph, Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for Diageo.',
      stakeStatement: 'Every minute of excess dwell time at Diageo\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Joseph, the yard is where Diageo\'s execution breaks down',
        subheadline: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Joseph, let\'s walk your yard network',
        subtext: '30-minute conversation about Diageo\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Joseph',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Joseph lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['cost per load', 'detention spend', 'labor cost per trailer', 'total cost of ownership'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Joseph\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-019',
        name: 'Jose Martins',
        firstName: 'Jose',
        lastName: 'Martins',
        title: 'Category Director, Logistics North America',
        company: 'Diageo',
        email: 'jose.martins@diageo.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Distribution / Logistics',
      },
      fallbackLane: 'logistics',
      label: 'Jose Martins - Category Director',
      variantSlug: 'jose-martins',

      framingNarrative: 'Jose, Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for Diageo.',
      stakeStatement: 'Every minute of excess dwell time at Diageo\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Jose, the yard is where Diageo\'s execution breaks down',
        subheadline: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Jose, let\'s walk your yard network',
        subtext: '30-minute conversation about Diageo\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Jose',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Jose lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Jose\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-020',
        name: 'Joshua Sallee',
        firstName: 'Joshua',
        lastName: 'Sallee',
        title: 'Procurement Category Manager',
        company: 'Diageo',
        email: 'joshua.sallee@diageo.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Transportation Procurement',
      },
      fallbackLane: 'logistics',
      label: 'Joshua Sallee - Procurement Category Manager',
      variantSlug: 'joshua-sallee',

      framingNarrative: 'Joshua, Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for Diageo.',
      stakeStatement: 'Every minute of excess dwell time at Diageo\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Joshua, the yard is where Diageo\'s execution breaks down',
        subheadline: 'Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Joshua, let\'s walk your yard network',
        subtext: '30-minute conversation about Diageo\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Joshua',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Joshua lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Joshua\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live', context: 'Measured across live deployments' },
        { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across comparable verticals' },
        { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
        { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at food & beverage facilities' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'It is accurate that your software has enabled us to take on additional volume while remaining headcount neutral in the dock office.',
        role: 'Operations Director',
        company: 'National CPG/Beverage Manufacturer',
      },
    },
  ],

  network: {
    facilityCount: '30+',
    facilityTypes: ['Distilleries', 'Bottling Plants', 'Aging Warehouses', 'Distribution Centers'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '1,500+ across network',
    fleet: '3PL-heavy with contract carriers; mix of dry, temp-controlled, and high-value spirits loads',
  },

  freight: {
    primaryModes: ['Truckload', 'Intermodal/Rail', 'LTL'],
    avgLoadsPerDay: '1,500+',
    peakSeason: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
  },

  signals: {
    modexAttendance: 'Past attendee list',
    recentNews: [
      'Public MODEX signal plus likely fit for multi-site execution standardization.',
    ],
    supplyChainInitiatives: ['Beverage flow is time-sensitive and network-heavy; YardFlow story should translate well from Primo.'],
    urgencyDriver: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
  },

  theme: {
    accentColor: '#2563EB',
    backgroundVariant: 'dark',
  },

  showcase: true,
  showcaseOrder: 6,
  layoutPreset: 'executive',
};
