/**
 * FedEx — ABM Microsite Data
 * Quality Tier: B
 * Generated by scripts/generate-microsite-data.ts
 * 
 * Sources:
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (5 named contacts)
 */

import type { AccountMicrositeData } from '../schema';

const BOOKING_LINK = 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2UyZRVDBYFwV3QOTx7-WK4APujmADpAGspAqeR5qAmK4KJjN2P1QNIrsVj0SPO0qMZIWKzuPoW';

// LEGACY SECTIONS (preserved for reference — M3.2-M3.6 may lift prose into memo sections)
/*
 * [
 *     {
 *       type: 'hero',
 *       headline: 'FedEx moves 200,000 trailers a day across 5,000 facilities. Even a 1% yard efficiency gain is worth hundreds of millions.',
 *       subheadline: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
 *       accountCallout: 'FedEx - 3PL / Logistics',
 *       backgroundTheme: 'dark',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for FedEx',
 *         subtext: '30-minute walk-through of your facility network with board-ready ROI.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *     },
 *     {
 *       type: 'problem',
 *       sectionLabel: 'The Hidden Constraint',
 *       headline: 'The yard is where FedEx\'s supply chain math breaks down',
 *       narrative: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
 *       painPoints: [
 *         {
 *           headline: 'Ground-Express integration creates unprecedented yard complexity',
 *           description: 'FedEx is merging Ground and Express into a single operating network. That means thousands of facilities need to handle both parcel sort and freight cross-dock operations through the same yards. The integration is the largest yard coordination challenge in logistics history.',
 *           kpiImpact: 'Network integration deadline: FY2027. Yard protocol unification is on the critical path.',
 *           relevantPeople: ['fedex-temple', 'fedex-hatton'],
 *         },
 *         {
 *           headline: 'Scale makes even fractional yard improvements worth nine figures',
 *           description: 'At 200,000+ daily trailer moves, a 1% improvement in average yard turn time saves FedEx more than most companies spend on their entire logistics budget. The math is not theoretical. It is operational leverage at unprecedented scale.',
 *           kpiImpact: '1% yard efficiency gain = $200M+ annual impact at FedEx scale',
 *           relevantPeople: ['fedex-temple', 'fedex-hatton'],
 *         },
 *         {
 *           headline: 'Strategic logo with long sales cycle requires opportunistic entry',
 *           description: 'FedEx is the ultimate strategic logo but the most complex sell. This is not a cold-call account. YardFlow needs a warm path, a pilot site, and patience. MODEX presence creates the opportunistic window.',
 *           kpiImpact: 'Treat as opportunistic: high upside, long cycle, need warm intro',
 *           relevantPeople: ['fedex-temple', 'fedex-hatton'],
 *         }
 *       ],
 *     },
 *     {
 *       type: 'stakes',
 *       sectionLabel: 'What This Costs You',
 *       headline: 'The math FedEx is not tracking in one place',
 *       narrative: 'FedEx is merging Ground and Express into a single operating network. That means thousands of facilities need to handle both parcel sort and freight cross-dock operations through the same yards. The integration is the largest yard coordination challenge in logistics history. Meanwhile, at 200,000+ daily trailer moves, a 1% improvement in average yard turn time saves FedEx more than most companies spend on their entire logistics budget. The math is not theoretical. It is operational leverage at unprecedented scale.',
 *       annualCost: '$5M-$8M in estimated yard-driven inefficiency across the network',
 *       costBreakdown: [
 *         { label: 'Carrier detention / demurrage', value: '$2M+' },
 *         { label: 'Dock contention and turn time excess', value: '$2M+' },
 *         { label: 'Gate and spotter labor overhead', value: '$2M+' },
 *         { label: 'Peak season surge inefficiency', value: '$1M+' },
 *       ],
 *       urgencyDriver: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
 *     },
 *     {
 *       type: 'solution',
 *       sectionLabel: 'The Fix',
 *       headline: 'One protocol across every FedEx yard',
 *       narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Same driver journey at every facility. same dock assignment logic. Variance dies. Throughput becomes calculable.',
 *       modules: [
 *         { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Standardizes verify across FedEx\'s facility network.' },
 *         { id: 'flowBOL', name: 'flowBOL', verb: 'Document', shortDescription: 'Touchless BOL creation with timestamped chain of custody.', relevanceToAccount: 'Standardizes document across FedEx\'s facility network.' },
 *         { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. No more radio dispatching.', relevanceToAccount: 'Standardizes execute across FedEx\'s facility network.' },
 *         { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Standardizes map across FedEx\'s facility network.' },
 *       ],
 *       accountFit: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
 *     },
 *     {
 *       type: 'proof',
 *       sectionLabel: 'Proof from Live Deployment',
 *       headline: 'Running today across 24 facilities',
 *       blocks: [
 *         {
 *           type: 'metric',
 *           stats: [
 *             { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol at comparable 3pl / logistics operations' },
 *             { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across similar verticals' },
 *             { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
 *             { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at 3pl / logistics facilities' },
 *           ],
 *         },
 *         {
 *           type: 'quote',
 *           quote: {
 *             text: 'Our customers see the difference. Carrier check-in went from 45 minutes to under 10. That changes the economics of every load we handle.',
 *             role: 'Operations Director',
 *             company: 'National 3PL Provider',
 *           },
 *         },
 *       ],
 *     },
 *     {
 *       type: 'network-map',
 *       sectionLabel: 'Your Network',
 *       headline: 'FedEx\'s yard network at scale',
 *       narrative: 'Every one of these facilities runs its own yard protocol today. Different gate processes, different spotter dispatch methods, different tribal knowledge. YardFlow gives you one standard across all of them.',
 *       facilityCount: '5,000+',
 *       facilityTypes: ['Ground Hubs', 'Express Hubs', 'Freight Service Centers', 'Cross-Docks'],
 *       geographicSpread: 'North America',
 *       dailyTrailerMoves: '200,000+ across the network',
 *     },
 *     {
 *       type: 'roi',
 *       sectionLabel: 'The Business Case',
 *       headline: 'Conservative ROI model for FedEx',
 *       narrative: 'Based on measured YardFlow improvements at comparable operations.',
 *       roiLines: [
 *         { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
 *         { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
 *         { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
 *         { label: 'Dock utilization', before: '65%', after: '85%', delta: '+20 pts', unit: 'utilization' },
 *       ],
 *       totalAnnualSavings: '$5M-$8M across the network',
 *       paybackPeriod: '< 6 months',
 *       methodology: 'Based on measured results at 24 live facilities extrapolated to FedEx facility count and operational profile.',
 *     },
 *     {
 *       type: 'testimonial',
 *       sectionLabel: 'From an Operator Who Runs It',
 *       quote: 'We went from managing yards on whiteboards to managing them on screens. The difference is not cosmetic. It is operational.',
 *       role: 'Operations Director',
 *       company: 'National 3PL Provider',
 *       context: 'After 12 months of full YardFlow deployment across their facility network.',
 *     },
 *     {
 *       type: 'cta',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for FedEx',
 *         subtext: 'We map your top 3 facilities, identify the throughput constraint, and build a board-ready rollout plan.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *       closingLine: 'One conversation. Your yard network. A clear path to $5M-$8M in annual savings.',
 *     },
 *   ]
 */

export const fedex: AccountMicrositeData = {
  slug: 'fedex',
  accountName: 'FedEx',
  parentBrand: 'FedEx',
  vertical: 'logistics-3pl',
  tier: 'Tier 3',
  band: 'D',
  priorityScore: 53,

  pageTitle: 'YardFlow for FedEx - Yard Network Standardization',
  metaDescription: 'How YardFlow eliminates the yard bottleneck across FedEx\'s facility network.',

  sections: [],

  people: [
    {
      personaId: 'P-071',
      name: 'Scott Temple',
      firstName: 'Scott',
      lastName: 'Temple',
      title: 'President, FedEx Supply Chain',
      company: 'FedEx',
      email: 'scott.temple@fedex.com',
      linkedinUrl: 'https://www.linkedin.com/in/scotttemple2',
      roleInDeal: 'decision-maker',
      seniority: 'C-level',
      function: 'Operations / Supply Chain',
      currentMandate: 'Best FedEx Supply Chain operating executive surfaced publicly.',
      bestIntroPath: 'LinkedIn / exec outreach',
    },
    {
      personaId: 'P-072',
      name: 'Ray Hatton',
      firstName: 'Ray',
      lastName: 'Hatton',
      title: 'Vice President, FedEx Supply Chain',
      company: 'FedEx',
      email: 'ray.hatton@fedex.com',
      linkedinUrl: 'https://www.linkedin.com/in/ray-hatton-18411356',
      roleInDeal: 'routing-contact',
      seniority: 'C-level',
      function: 'Operations',
      currentMandate: 'Named VP-level FedEx Supply Chain operator.',
      bestIntroPath: 'LinkedIn / exec outreach',
    },
    {
      personaId: 'P-073',
      name: 'Jose A. Touzon',
      firstName: 'Jose',
      lastName: 'A. Touzon',
      title: 'Vice President, Customer Operations',
      company: 'FedEx',
      email: 'jose.touzon@fedex.com',
      linkedinUrl: 'https://www.linkedin.com/in/jose-a-touzon-7763423',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Customer Operations',
      currentMandate: 'Public profile says he leads FedEx supply-chain operations for technology and industrial clients in North America.',
      bestIntroPath: 'LinkedIn / exec outreach',
    },
    {
      personaId: 'P-074',
      name: 'Douglas Spamer',
      firstName: 'Douglas',
      lastName: 'Spamer',
      title: 'Managing Director - Linehaul / Transportation, FedEx Ground',
      company: 'FedEx',
      email: 'douglas.spamer@fedex.com',
      linkedinUrl: 'https://www.linkedin.com/in/douglas-spamer-65794a30',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Linehaul / Transportation',
      currentMandate: 'Direct linehaul and transportation signal inside FedEx Ground.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-075',
      name: 'Jake Pyke',
      firstName: 'Jake',
      lastName: 'Pyke',
      title: 'Senior Manager - Linehaul Operations',
      company: 'FedEx',
      email: 'jake.pyke@fedex.com',
      linkedinUrl: 'https://www.linkedin.com/in/jake-pyke-5738a5185',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Terminal / Network Operations',
      currentMandate: 'Named linehaul operations manager for network-ops lane.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'P-071',
        name: 'Scott Temple',
        firstName: 'Scott',
        lastName: 'Temple',
        title: 'President, FedEx Supply Chain',
        company: 'FedEx',
        email: 'scott.temple@fedex.com',
        roleInDeal: 'decision-maker',
        seniority: 'C-level',
        function: 'Operations / Supply Chain',
      },
      fallbackLane: 'ops',
      label: 'Scott Temple - President',
      variantSlug: 'scott-temple',

      framingNarrative: 'Scott, Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for FedEx.',
      stakeStatement: 'Every minute of excess dwell time at FedEx\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Scott, the yard is where FedEx\'s execution breaks down',
        subheadline: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Scott, let\'s walk your yard network',
        subtext: '30-minute conversation about FedEx\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Scott',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Strategic, board-level. Reference Scott\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Scott\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-072',
        name: 'Ray Hatton',
        firstName: 'Ray',
        lastName: 'Hatton',
        title: 'Vice President, FedEx Supply Chain',
        company: 'FedEx',
        email: 'ray.hatton@fedex.com',
        roleInDeal: 'routing-contact',
        seniority: 'C-level',
        function: 'Operations',
      },
      fallbackLane: 'ops',
      label: 'Ray Hatton - Vice President',
      variantSlug: 'ray-hatton',

      framingNarrative: 'Ray, Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for FedEx.',
      stakeStatement: 'Every minute of excess dwell time at FedEx\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Ray, the yard is where FedEx\'s execution breaks down',
        subheadline: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Ray, let\'s walk your yard network',
        subtext: '30-minute conversation about FedEx\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Ray',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Strategic, board-level. Reference Ray\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Ray\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-073',
        name: 'Jose A. Touzon',
        firstName: 'Jose',
        lastName: 'A. Touzon',
        title: 'Vice President, Customer Operations',
        company: 'FedEx',
        email: 'jose.touzon@fedex.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Customer Operations',
      },
      fallbackLane: 'ops',
      label: 'Jose A. Touzon - Vice President',
      variantSlug: 'jose-a-touzon',

      framingNarrative: 'Jose, Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for FedEx.',
      stakeStatement: 'Every minute of excess dwell time at FedEx\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Jose, the yard is where FedEx\'s execution breaks down',
        subheadline: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Jose, let\'s walk your yard network',
        subtext: '30-minute conversation about FedEx\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Jose',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Jose lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Jose\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-074',
        name: 'Douglas Spamer',
        firstName: 'Douglas',
        lastName: 'Spamer',
        title: 'Managing Director - Linehaul / Transportation, FedEx Ground',
        company: 'FedEx',
        email: 'douglas.spamer@fedex.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Linehaul / Transportation',
      },
      fallbackLane: 'logistics',
      label: 'Douglas Spamer - Managing Director - Linehaul / Transportation',
      variantSlug: 'douglas-spamer',

      framingNarrative: 'Douglas, Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for FedEx.',
      stakeStatement: 'Every minute of excess dwell time at FedEx\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Douglas, the yard is where FedEx\'s execution breaks down',
        subheadline: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Douglas, let\'s walk your yard network',
        subtext: '30-minute conversation about FedEx\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Douglas',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Douglas lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Douglas\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-075',
        name: 'Jake Pyke',
        firstName: 'Jake',
        lastName: 'Pyke',
        title: 'Senior Manager - Linehaul Operations',
        company: 'FedEx',
        email: 'jake.pyke@fedex.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Terminal / Network Operations',
      },
      fallbackLane: 'ops',
      label: 'Jake Pyke - Senior Manager - Linehaul Operations',
      variantSlug: 'jake-pyke',

      framingNarrative: 'Jake, Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      openingHook: 'Public MODEX signal plus likely fit for multi-site execution standardization. - the yard is where execution meets reality for FedEx.',
      stakeStatement: 'Every minute of excess dwell time at FedEx\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Jake, the yard is where FedEx\'s execution breaks down',
        subheadline: 'Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Jake, let\'s walk your yard network',
        subtext: '30-minute conversation about FedEx\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Jake',
        personContext: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
      },

      toneShift: 'Operator-to-operator. Jake lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Jake\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live', context: 'Measured across live deployments' },
        { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across comparable verticals' },
        { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
        { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at 3pl / logistics facilities' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'Our customers see the difference. Carrier check-in went from 45 minutes to under 10. That changes the economics of every load.',
        role: 'Operations Director',
        company: 'National 3PL Provider',
      },
    },
  ],

  network: {
    facilityCount: '5,000+',
    facilityTypes: ['Ground Hubs', 'Express Hubs', 'Freight Service Centers', 'Cross-Docks'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '200,000+ across network',
    fleet: 'Massive private fleet: 200K+ vehicles, plus contracted linehaul',
  },

  freight: {
    primaryModes: ['Truckload', 'LTL'],
    avgLoadsPerDay: '200,000+',
    peakSeason: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
  },

  signals: {
    modexAttendance: 'Past attendee list',
    recentNews: [
      'Public MODEX signal plus likely fit for multi-site execution standardization.',
    ],
    supplyChainInitiatives: ['Useful strategic logo, but more complex sell. Treat as opportunistic unless a warm path appears.'],
    urgencyDriver: 'Public MODEX signal plus likely fit for multi-site execution standardization.',
  },

  theme: {
    accentColor: '#0891B2',
    backgroundVariant: 'dark',
  },


};
