/**
 * ABM Microsite Factory — Account Data Index
 *
 * Central registry for all account microsite data files.
 * Auto-generated by scripts/generate-microsite-data.ts
 */

import type { AccountMicrositeData } from '../schema';

import { abInbev } from './ab-inbev';
import { barnesNoble } from './barnes-noble';
import { campbellS } from './campbell-s';
import { caterpillar } from './caterpillar';
import { cocaCola } from './coca-cola';
import { constellationBrands } from './constellation-brands';
import { dannon } from './dannon';
import { diageo } from './diageo';
import { fedex } from './fedex';
import { ford } from './ford';
import { fritoLay } from './frito-lay';
import { generalMills } from './general-mills';
import { georgiaPacific } from './georgia-pacific';
import { hEB } from './h-e-b';
import { honda } from './honda';
import { hormelFoods } from './hormel-foods';
import { hyundaiMotorAmerica } from './hyundai-motor-america';
import { jmSmucker } from './jm-smucker';
import { johnDeere } from './john-deere';
import { kencoLogisticsServices } from './kenco-logistics-services';
import { keurigDrPepper } from './keurig-dr-pepper';
import { mondelezInternational } from './mondelez-international';
import { performanceFoodGroup } from './performance-food-group';
import { theHomeDepot } from './the-home-depot';
import { toyota } from './toyota';

const ACCOUNTS: Record<string, AccountMicrositeData> = {
  'ab-inbev': abInbev,
  'barnes-noble': barnesNoble,
  'campbell-s': campbellS,
  'caterpillar': caterpillar,
  'coca-cola': cocaCola,
  'constellation-brands': constellationBrands,
  'dannon': dannon,
  'diageo': diageo,
  'fedex': fedex,
  'ford': ford,
  'frito-lay': fritoLay,
  'general-mills': generalMills,
  'georgia-pacific': georgiaPacific,
  'h-e-b': hEB,
  'honda': honda,
  'hormel-foods': hormelFoods,
  'hyundai-motor-america': hyundaiMotorAmerica,
  'jm-smucker': jmSmucker,
  'john-deere': johnDeere,
  'kenco-logistics-services': kencoLogisticsServices,
  'keurig-dr-pepper': keurigDrPepper,
  'mondelez-international': mondelezInternational,
  'performance-food-group': performanceFoodGroup,
  'the-home-depot': theHomeDepot,
  'toyota': toyota,
};

export function getAccountMicrositeData(slug: string): AccountMicrositeData | null {
  return ACCOUNTS[slug] ?? null;
}

export function getAllMicrositeSlugs(): string[] {
  return Object.keys(ACCOUNTS);
}

export function getAllAccountMicrositeData(): AccountMicrositeData[] {
  return Object.values(ACCOUNTS);
}
