/**
 * Kenco Logistics Services — ABM Microsite Data
 * Quality Tier: B
 * Generated by scripts/generate-microsite-data.ts
 * 
 * Sources:
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (5 named contacts)
 */

import type { AccountMicrositeData } from '../schema';


// LEGACY SECTIONS (preserved for reference — M3.2-M3.6 may lift prose into memo sections)
/*
 * [
 *     {
 *       type: 'hero',
 *       headline: 'Kenco manages 100+ warehouses for other companies. Every client yard runs differently. YardFlow is the protocol that standardizes them all.',
 *       subheadline: 'Less direct logo hunt, more partnership / ecosystem / referral opportunity.',
 *       accountCallout: 'Kenco Logistics Services - 3PL / Logistics',
 *       backgroundTheme: 'dark',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Kenco Logistics Services',
 *         subtext: '30-minute walk-through of your facility network with board-ready ROI.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *     },
 *     {
 *       type: 'problem',
 *       sectionLabel: 'The Hidden Constraint',
 *       headline: 'The yard is where Kenco Logistics Services\'s supply chain math breaks down',
 *       narrative: 'Less direct logo hunt, more partnership / ecosystem / referral opportunity.',
 *       painPoints: [
 *         {
 *           headline: 'Contract logistics means managing 100 different yard protocols for 100 different clients',
 *           description: 'Kenco operates warehouses and DCs for dozens of different shippers, each with different carrier requirements, dock door preferences, and yard rules. The operational complexity is not the warehouse. It is the yard outside the warehouse, multiplied by every client contract.',
 *           kpiImpact: 'Yard protocol fragmentation across 100+ client-operated facilities',
 *           relevantPeople: ['kenco-logistics-services-montgomery', 'kenco-logistics-services-weber'],
 *         },
 *         {
 *           headline: 'Innovation VP is speaking at MODEX, which means Kenco is buying, not browsing',
 *           description: 'Kristi Montgomery, Kenco\'s VP of Innovation, is a named session speaker at MODEX 2026. When the innovation leader is on stage, the operations team is walking the floor looking for technology to bring back.',
 *           kpiImpact: 'Highest-quality MODEX signal: named speaker indicates active technology evaluation',
 *           relevantPeople: ['kenco-logistics-services-montgomery', 'kenco-logistics-services-weber'],
 *         },
 *         {
 *           headline: 'YardFlow as a multi-client yard protocol is a partnership play, not a single sale',
 *           description: 'If Kenco standardizes on YardFlow across their 100+ managed facilities, every one of their clients gets yard visibility. This is not a single logo sale. It is a distribution channel for YardFlow into dozens of enterprise supply chains.',
 *           kpiImpact: 'Partnership potential: 1 contract = 100+ facility deployments',
 *           relevantPeople: ['kenco-logistics-services-montgomery', 'kenco-logistics-services-weber'],
 *         }
 *       ],
 *     },
 *     {
 *       type: 'stakes',
 *       sectionLabel: 'What This Costs You',
 *       headline: 'The math Kenco Logistics Services is not tracking in one place',
 *       narrative: 'Kenco operates warehouses and DCs for dozens of different shippers, each with different carrier requirements, dock door preferences, and yard rules. The operational complexity is not the warehouse. It is the yard outside the warehouse, multiplied by every client contract. Meanwhile, kristi Montgomery, Kenco\'s VP of Innovation, is a named session speaker at MODEX 2026. When the innovation leader is on stage, the operations team is walking the floor looking for technology to bring back.',
 *       annualCost: '$5M-$8M in estimated yard-driven inefficiency across the network',
 *       costBreakdown: [
 *         { label: 'Carrier detention / demurrage', value: '$2M+' },
 *         { label: 'Dock contention and turn time excess', value: '$2M+' },
 *         { label: 'Gate and spotter labor overhead', value: '$2M+' },
 *         { label: 'Peak season surge inefficiency', value: '$1M+' },
 *       ],
 *       urgencyDriver: 'Named session speaker indicates event involvement.',
 *     },
 *     {
 *       type: 'solution',
 *       sectionLabel: 'The Fix',
 *       headline: 'One protocol across every Kenco Logistics Services yard',
 *       narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Same driver journey at every facility. same dock assignment logic. Variance dies. Throughput becomes calculable.',
 *       modules: [
 *         { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Standardizes verify across Kenco Logistics Services\'s facility network.' },
 *         { id: 'flowBOL', name: 'flowBOL', verb: 'Document', shortDescription: 'Touchless BOL creation with timestamped chain of custody.', relevanceToAccount: 'Standardizes document across Kenco Logistics Services\'s facility network.' },
 *         { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. No more radio dispatching.', relevanceToAccount: 'Standardizes execute across Kenco Logistics Services\'s facility network.' },
 *         { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Standardizes map across Kenco Logistics Services\'s facility network.' },
 *       ],
 *       accountFit: 'Less direct logo hunt, more partnership / ecosystem / referral opportunity.',
 *     },
 *     {
 *       type: 'proof',
 *       sectionLabel: 'Proof from Live Deployment',
 *       headline: 'Running today across 24 facilities',
 *       blocks: [
 *         {
 *           type: 'metric',
 *           stats: [
 *             { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol at comparable 3pl / logistics operations' },
 *             { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across similar verticals' },
 *             { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
 *             { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at 3pl / logistics facilities' },
 *           ],
 *         },
 *         {
 *           type: 'quote',
 *           quote: {
 *             text: 'Our customers see the difference. Carrier check-in went from 45 minutes to under 10. That changes the economics of every load we handle.',
 *             role: 'Operations Director',
 *             company: 'National 3PL Provider',
 *           },
 *         },
 *       ],
 *     },
 *     {
 *       type: 'network-map',
 *       sectionLabel: 'Your Network',
 *       headline: 'Kenco Logistics Services\'s yard network at scale',
 *       narrative: 'Every one of these facilities runs its own yard protocol today. Different gate processes, different spotter dispatch methods, different tribal knowledge. YardFlow gives you one standard across all of them.',
 *       facilityCount: '100+',
 *       facilityTypes: ['Contract Warehouses', 'Distribution Centers', 'Cross-Docks', 'Managed Transportation Hubs'],
 *       geographicSpread: 'North America',
 *       dailyTrailerMoves: '5,000+ across the network',
 *     },
 *     {
 *       type: 'roi',
 *       sectionLabel: 'The Business Case',
 *       headline: 'Conservative ROI model for Kenco Logistics Services',
 *       narrative: 'Based on measured YardFlow improvements at comparable operations.',
 *       roiLines: [
 *         { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
 *         { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
 *         { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
 *         { label: 'Dock utilization', before: '65%', after: '85%', delta: '+20 pts', unit: 'utilization' },
 *       ],
 *       totalAnnualSavings: '$5M-$8M across the network',
 *       paybackPeriod: '< 6 months',
 *       methodology: 'Based on measured results at 24 live facilities extrapolated to Kenco Logistics Services facility count and operational profile.',
 *     },
 *     {
 *       type: 'testimonial',
 *       sectionLabel: 'From an Operator Who Runs It',
 *       quote: 'We went from managing yards on whiteboards to managing them on screens. The difference is not cosmetic. It is operational.',
 *       role: 'Operations Director',
 *       company: 'National 3PL Provider',
 *       context: 'After 12 months of full YardFlow deployment across their facility network.',
 *     },
 *     {
 *       type: 'cta',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for Kenco Logistics Services',
 *         subtext: 'We map your top 3 facilities, identify the throughput constraint, and build a board-ready rollout plan.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *       closingLine: 'One conversation. Your yard network. A clear path to $5M-$8M in annual savings.',
 *     },
 *   ]
 */

export const kencoLogisticsServices: AccountMicrositeData = {
  slug: 'kenco-logistics-services',
  accountName: 'Kenco Logistics Services',
  parentBrand: 'Kenco',
  vertical: 'logistics-3pl',
  tier: 'Tier 3',
  band: 'D',
  priorityScore: 61,

  pageTitle: 'YardFlow for Kenco Logistics Services - Yard Network Standardization',
  metaDescription: 'How YardFlow eliminates the yard bottleneck across Kenco Logistics Services\'s facility network.',

  sections: [],

  people: [
    {
      personaId: 'P-061',
      name: 'Kristi Montgomery',
      firstName: 'Kristi',
      lastName: 'Montgomery',
      title: 'Vice President of Strategic Transformation',
      company: 'Kenco Logistics Services',
      email: 'kristi.montgomery@kencogroup.com',
      linkedinUrl: 'https://kencogroup.com/news/kristi-montgomery-vp-strategic-transformation/',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Innovation / Strategy',
      currentMandate: 'Officially named Kenco transformation leader and recurring industry conference speaker.',
      bestIntroPath: 'Conference / ecosystem outreach',
    },
    {
      personaId: 'P-062',
      name: 'Shanon Weber',
      firstName: 'Shanon',
      lastName: 'Weber',
      title: 'Group Vice President, Operations',
      company: 'Kenco Logistics Services',
      email: 'shanon.weber@kencogroup.com',
      linkedinUrl: 'https://www.linkedin.com/in/shanon-weber-a7b9328',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Operations',
      currentMandate: 'Named Kenco operations executive.',
      bestIntroPath: 'LinkedIn / ecosystem outreach',
    },
    {
      personaId: 'P-063',
      name: 'Jason Minghini',
      firstName: 'Jason',
      lastName: 'Minghini',
      title: 'Engineering leader, Kenco Group',
      company: 'Kenco Logistics Services',
      email: 'jason.minghini@kencogroup.com',
      linkedinUrl: 'https://www.linkedin.com/in/jason-minghini-mba-806b4812',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Engineering / Solutions',
      currentMandate: 'Public profile says he leads engineering facets across Kenco.',
      bestIntroPath: 'LinkedIn / ecosystem outreach',
    },
    {
      personaId: 'P-064',
      name: 'Emmanuel (Pete) Bradley',
      firstName: 'Emmanuel',
      lastName: '(Pete) Bradley',
      title: 'Operations executive',
      company: 'Kenco Logistics Services',
      email: 'emmanuel.bradley@kencogroup.com',
      linkedinUrl: 'https://www.linkedin.com/in/emmanuel-pete-bradley-9b90b128',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Operations',
      currentMandate: 'Named large-scale distribution and operations leader at Kenco.',
      bestIntroPath: 'LinkedIn / ecosystem outreach',
    },
    {
      personaId: 'P-065',
      name: 'Andre Pereira',
      firstName: 'Andre',
      lastName: 'Pereira',
      title: 'General Manager, Kenco Group',
      company: 'Kenco Logistics Services',
      email: 'andre.pereira@kencogroup.com',
      linkedinUrl: 'https://www.linkedin.com/in/andr%C3%A9-luiz-pereira',
      roleInDeal: 'routing-contact',
      seniority: 'Director',
      function: 'Customer Operations',
      currentMandate: 'Named GM with operational excellence angle at Kenco.',
      bestIntroPath: 'LinkedIn / ecosystem outreach',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'P-061',
        name: 'Kristi Montgomery',
        firstName: 'Kristi',
        lastName: 'Montgomery',
        title: 'Vice President of Strategic Transformation',
        company: 'Kenco Logistics Services',
        email: 'kristi.montgomery@kencogroup.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Innovation / Strategy',
      },
      fallbackLane: 'executive',
      label: 'Kristi Montgomery - Vice President of Strategic Transformation',
      variantSlug: 'kristi-montgomery',

      framingNarrative: "Kristi's public speaking at MODEX and ProMat positions her as the most visible transformation advocate in the 3PL innovation space. Her agenda items — warehouse automation, carrier integration, last-mile visibility — are all upstream of the yard execution layer YardFlow operates on. The partnership conversation is: 'what's the yard execution standard for the 100 shippers you manage, and who sets it?'",
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Kenco Logistics Services.',
      stakeStatement: 'Every minute of excess dwell time at Kenco Logistics Services\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Kristi, the yard is where Kenco Logistics Services\'s execution breaks down',
        subheadline: "Kenco manages 100+ warehouses for 70+ enterprise clients. Each client has different carrier requirements, different dock rules, different yard protocols. The operational complexity isn't the warehouse — it's the yard outside the warehouse, multiplied by 70 different shipper contracts. A single yard operating standard applied at the managed-services level would deliver 100+ deployments from one partnership decision.",
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],

      toneShift: 'Operator-to-operator. Kristi lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'detention cost', 'throughput', 'operational efficiency'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Kristi\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-062',
        name: 'Shanon Weber',
        firstName: 'Shanon',
        lastName: 'Weber',
        title: 'Group Vice President, Operations',
        company: 'Kenco Logistics Services',
        email: 'shanon.weber@kencogroup.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Operations',
      },
      fallbackLane: 'ops',
      label: 'Shanon Weber - Group Vice President',
      variantSlug: 'shanon-weber',

      framingNarrative: 'Shanon leads operations across Kenco\'s managed-services portfolio — 100+ warehouses, dozens of client contracts, each with different carrier protocols and dock rules. The operational complexity at Kenco is not warehouse automation; it is the yard outside each warehouse, where client-specific carrier requirements collide with Kenco\'s standardized service delivery. A single yard operating standard across managed facilities is the margin lever that sits below the WMS.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Kenco Logistics Services.',
      stakeStatement: 'Every minute of excess dwell time at Kenco Logistics Services\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Shanon, the yard is where Kenco Logistics Services\'s execution breaks down',
        subheadline: "Kenco's operations portfolio spans 100+ managed warehouses. The variance across those facilities isn't warehouse automation — it's the yard outside each one, where client carrier protocols diverge and dwell time accumulates below the WMS visibility threshold. Standardizing the yard layer at the managed-services tier is the operations lever Kenco controls directly.",
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],

      toneShift: 'Operator-to-operator. Shanon lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Shanon\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-063',
        name: 'Jason Minghini',
        firstName: 'Jason',
        lastName: 'Minghini',
        title: 'Engineering leader, Kenco Group',
        company: 'Kenco Logistics Services',
        email: 'jason.minghini@kencogroup.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Engineering / Solutions',
      },
      fallbackLane: 'ops',
      label: 'Jason Minghini - Engineering leader',
      variantSlug: 'jason-minghini',

      framingNarrative: 'Jason leads engineering and solutions design across Kenco\'s facility portfolio — the team that specifies warehouse automation, conveyor integration, and dock configuration for new client builds. Every engineered facility has a yard outside it. The yard is typically designed last, specified loosely, and operated manually long after the warehouse automation is live. Integrating a yard execution standard into the solution design phase is the gap Jason\'s team is positioned to close.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Kenco Logistics Services.',
      stakeStatement: 'Every minute of excess dwell time at Kenco Logistics Services\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Jason, the yard is where Kenco Logistics Services\'s execution breaks down',
        subheadline: "Kenco's engineering team specifies the warehouse automation, conveyor integration, and dock layout for each managed facility build. The yard outside the dock is the one system that typically gets specified last and operated manually after go-live. Integrating a yard execution protocol into the facility engineering scope closes the gap between the warehouse automation and the carrier arrival.",
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],

      toneShift: 'Operator-to-operator. Jason lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'detention cost', 'throughput', 'operational efficiency'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Jason\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-064',
        name: 'Emmanuel (Pete) Bradley',
        firstName: 'Emmanuel',
        lastName: '(Pete) Bradley',
        title: 'Operations executive',
        company: 'Kenco Logistics Services',
        email: 'emmanuel.bradley@kencogroup.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Operations',
      },
      fallbackLane: 'ops',
      label: 'Emmanuel (Pete) Bradley - Operations executive',
      variantSlug: 'emmanuel-pete-bradley',

      framingNarrative: 'Emmanuel leads large-scale distribution operations at Kenco — the day-to-day execution layer across managed warehouses and DCs. At that operational scale, 70+ client contracts means 70+ different carrier protocols, 70+ different dock rules, and 70+ different yard operating norms. The referral path is direct: a yard operating standard that Kenco applies at the managed-services level is a decision Emmanuel\'s team makes once and deploys across the entire client base.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Kenco Logistics Services.',
      stakeStatement: 'Every minute of excess dwell time at Kenco Logistics Services\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Emmanuel, the yard is where Kenco Logistics Services\'s execution breaks down',
        subheadline: "Large-scale distribution at Kenco means managing 70+ client carrier contracts through a single operations team. Each client's carrier has different check-in expectations, dock preferences, and yard dwell tolerances. A yard operating standard applied across managed facilities removes the per-client protocol negotiation from daily operations.",
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],

      toneShift: 'Operator-to-operator. Emmanuel lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Emmanuel\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-065',
        name: 'Andre Pereira',
        firstName: 'Andre',
        lastName: 'Pereira',
        title: 'General Manager, Kenco Group',
        company: 'Kenco Logistics Services',
        email: 'andre.pereira@kencogroup.com',
        roleInDeal: 'routing-contact',
        seniority: 'Director',
        function: 'Customer Operations',
      },
      fallbackLane: 'ops',
      label: 'Andre Pereira - General Manager',
      variantSlug: 'andre-pereira',

      framingNarrative: 'Andre manages a Kenco facility at the general manager level — the operational layer closest to daily yard execution. The client relationship for each managed facility runs through the GM, which means the yard protocol decision is made at the site level before it reaches corporate. Andre\'s view on what a standardized yard operating layer would change in daily operations is the conversation that converts a partnership discussion into a deployment plan.',
      openingHook: 'Named session speaker indicates event involvement. - the yard is where execution meets reality for Kenco Logistics Services.',
      stakeStatement: 'Every minute of excess dwell time at Kenco Logistics Services\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Andre, the yard is where Kenco Logistics Services\'s execution breaks down',
        subheadline: "General manager at a Kenco managed facility means owning the client relationship and the daily yard operation simultaneously. The yard is where carrier delays become client service issues — and where a digital execution layer replaces the radio dispatch and paper log that currently mediate between the two.",
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],

      toneShift: 'Operator-to-operator. Andre lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Andre\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live', context: 'Measured across live deployments' },
        { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across comparable verticals' },
        { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
        { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at 3pl / logistics facilities' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'Our customers see the difference. Carrier check-in went from 45 minutes to under 10. That changes the economics of every load.',
        role: 'Operations Director',
        company: 'National 3PL Provider',
      },
    },
  ],

  network: {
    facilityCount: '100+',
    facilityTypes: ['Contract Warehouses', 'Distribution Centers', 'Cross-Docks', 'Managed Transportation Hubs'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '5,000+ across network',
    fleet: 'Customer-dependent: manages yards for dozens of different shippers',
  },

  freight: {
    primaryModes: ['Truckload', 'LTL'],
    avgLoadsPerDay: '5,000+',
    peakSeason: 'Named session speaker indicates event involvement.',
  },

  signals: {
    eventAttendance: 'Named speaker',
    recentNews: [
      'Named session speaker indicates event involvement.',
    ],
    supplyChainInitiatives: [
      'Network-wide yard operating standard for 100+ managed warehouses',
      'Multi-client carrier protocol mediation across 70+ shipper contracts',
    ],
    urgencyDriver: 'Named session speaker indicates event involvement.',
  },

  theme: {
    accentColor: '#0891B2',
    backgroundVariant: 'dark',
  },


};
