/**
 * The Home Depot — ABM Microsite Data
 * Quality Tier: A
 * Generated by scripts/generate-microsite-data.ts
 * 
 * Sources:
 *   - accounts.json (priority scoring, signals)
 *   - personas.json (8 named contacts)
 */

import type { AccountMicrositeData } from '../schema';

const BOOKING_LINK = 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2UyZRVDBYFwV3QOTx7-WK4APujmADpAGspAqeR5qAmK4KJjN2P1QNIrsVj0SPO0qMZIWKzuPoW';

// LEGACY SECTIONS (preserved for reference — M3.2-M3.6 may lift prose into memo sections)
/*
 * [
 *     {
 *       type: 'hero',
 *       headline: 'Home Depot\'s CFO is keynoting MODEX 2026. Their DC network moves 10,000+ trailers a day. We should be in that conversation.',
 *       subheadline: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
 *       accountCallout: 'The Home Depot - Retail',
 *       backgroundTheme: 'dark',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for The Home Depot',
 *         subtext: '30-minute walk-through of your facility network with board-ready ROI.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *     },
 *     {
 *       type: 'problem',
 *       sectionLabel: 'The Hidden Constraint',
 *       headline: '2,300 stores. 80+ DCs. Every trailer sitting idle at a dock is a missed replenishment window.',
 *       narrative: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
 *       painPoints: [
 *         {
 *           headline: '200+ facility yards with no standardized gate-to-dock protocol',
 *           description: 'The Home Depot operates the largest retail distribution network in home improvement, across RDCs, SDCs, DFCs, and flatbed DCs. Each facility type runs its own yard coordination. At 200+ sites, the variance is not a rounding error, it is a cost center.',
 *           kpiImpact: '$50M+ in estimated annual yard-driven inefficiency across the DC network',
 *           relevantPeople: ['the-home-depot-deaton', 'the-home-depot-drake'],
 *         },
 *         {
 *           headline: 'Pro and flatbed deliveries create yard complexity retail systems ignore',
 *           description: 'Home Depot is not just retail replenishment. Pro contractor delivery, flatbed staging, and will-call pickup create mixed-use yards that standard retail YMS cannot handle. Every flatbed DC is a different operational animal.',
 *           kpiImpact: 'Pro segment growing 2x faster than DIY, compounding yard complexity',
 *           relevantPeople: ['the-home-depot-deaton', 'the-home-depot-drake'],
 *         },
 *         {
 *           headline: 'Peak-season replenishment spikes overwhelm manual yard coordination at 80+ DCs',
 *           description: 'Home Depot\'s holiday and spring season surges push trailer volume 40-60% above baseline across every DC type. Manual yard coordination that barely works at average volume collapses during peaks. Overtime hours spike, dock utilization drops, and replenishment windows get missed.',
 *           kpiImpact: '$15M+ in peak-season overtime and missed replenishment across the DC network',
 *           relevantPeople: ['the-home-depot-deaton', 'the-home-depot-drake'],
 *         }
 *       ],
 *     },
 *     {
 *       type: 'stakes',
 *       sectionLabel: 'What This Costs You',
 *       headline: 'The math The Home Depot is not tracking in one place',
 *       narrative: 'The Home Depot operates the largest retail distribution network in home improvement, across RDCs, SDCs, DFCs, and flatbed DCs. Each facility type runs its own yard coordination. At 200+ sites, the variance is not a rounding error, it is a cost center. Meanwhile, home Depot is not just retail replenishment. Pro contractor delivery, flatbed staging, and will-call pickup create mixed-use yards that standard retail YMS cannot handle. Every flatbed DC is a different operational animal.',
 *       annualCost: '$5M-$8M in estimated yard-driven inefficiency across the network',
 *       costBreakdown: [
 *         { label: 'Carrier detention / demurrage', value: '$2M+' },
 *         { label: 'Dock contention and turn time excess', value: '$2M+' },
 *         { label: 'Gate and spotter labor overhead', value: '$2M+' },
 *         { label: 'Peak season surge inefficiency', value: '$1M+' },
 *       ],
 *       urgencyDriver: 'Official keynote tie gives unusually strong event signal.',
 *     },
 *     {
 *       type: 'solution',
 *       sectionLabel: 'The Fix',
 *       headline: 'One protocol across every The Home Depot yard',
 *       narrative: 'YardFlow replaces the patchwork of local yard practices with a single standardized operating protocol. Same driver journey at every facility. same dock assignment logic. Variance dies. Throughput becomes calculable.',
 *       modules: [
 *         { id: 'flowDRIVER', name: 'flowDRIVER', verb: 'Verify', shortDescription: 'Digital driver check-in to check-out. QR + wallet ID verification, algorithmic lane direction.', relevanceToAccount: 'Automates gate check-in across 200+ DCs. One process for RDCs, SDCs, and flatbed yards.' },
 *         { id: 'flowBOL', name: 'flowBOL', verb: 'Document', shortDescription: 'Touchless BOL creation with timestamped chain of custody.', relevanceToAccount: 'Captures BOL data at the gate so dock assignment starts before the driver parks.' },
 *         { id: 'flowSPOTTER', name: 'flowSPOTTER', verb: 'Execute', shortDescription: 'Spotter app for move execution and task queues. No more radio dispatching.', relevanceToAccount: 'Sequences trailers to dock doors across mixed-use yards. Flatbed, dry van, LTL - handled.' },
 *         { id: 'flowTWIN', name: 'flowTWIN', verb: 'Map', shortDescription: 'Digital twin of the yard. Real-time trailer location, dwell, and lane state.', relevanceToAccount: 'Network-wide dwell visibility across every facility type. CFO-ready throughput data.' },
 *       ],
 *       accountFit: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
 *     },
 *     {
 *       type: 'proof',
 *       sectionLabel: 'Proof from Live Deployment',
 *       headline: 'Running today across 24 facilities',
 *       blocks: [
 *         {
 *           type: 'metric',
 *           stats: [
 *             { value: '24', label: 'Facilities Live', context: 'Running the full YardFlow protocol at comparable retail operations' },
 *             { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across similar verticals' },
 *             { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
 *             { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at retail facilities' },
 *           ],
 *         },
 *         {
 *           type: 'quote',
 *           quote: {
 *             text: 'The yard used to be where we lost visibility. Now it is where we gain control over every trailer in the network. The dock office runs itself.',
 *             role: 'Operations Director',
 *             company: 'National Retail Distributor',
 *           },
 *         },
 *       ],
 *     },
 *     {
 *       type: 'network-map',
 *       sectionLabel: 'Your Network',
 *       headline: 'The Home Depot\'s yard network at scale',
 *       narrative: 'Every one of these facilities runs its own yard protocol today. Different gate processes, different spotter dispatch methods, different tribal knowledge. YardFlow gives you one standard across all of them.',
 *       facilityCount: '200+',
 *       facilityTypes: ['Rapid Deployment Centers', 'Stocking Distribution Centers', 'Direct Fulfillment Centers', 'Flatbed Distribution Centers'],
 *       geographicSpread: 'North America',
 *       dailyTrailerMoves: '10,000+ across the network',
 *     },
 *     {
 *       type: 'roi',
 *       sectionLabel: 'The Business Case',
 *       headline: 'Conservative ROI model for The Home Depot',
 *       narrative: 'Based on measured YardFlow improvements at comparable operations.',
 *       roiLines: [
 *         { label: 'Avg truck turn time', before: '48 min', after: '24 min', delta: '-50%', unit: 'minutes' },
 *         { label: 'Carrier detention per facility', before: '$80K/yr', after: '$40K/yr', delta: '-$40K', unit: 'per site' },
 *         { label: 'Gate labor per facility', before: '2.5 FTE', after: '1.5 FTE', delta: '-1 FTE', unit: 'per site' },
 *         { label: 'Dock utilization', before: '65%', after: '85%', delta: '+20 pts', unit: 'utilization' },
 *       ],
 *       totalAnnualSavings: '$5M-$8M across the network',
 *       paybackPeriod: '< 6 months',
 *       methodology: 'Based on measured results at 24 live facilities extrapolated to The Home Depot facility count and operational profile.',
 *     },
 *     {
 *       type: 'testimonial',
 *       sectionLabel: 'From an Operator Who Runs It',
 *       quote: 'Before YardFlow, we had 30 trailers in the yard and no idea which ones were loaded. Now every trailer has a status and a plan.',
 *       role: 'Operations Director',
 *       company: 'National Retail Distributor',
 *       context: 'After 12 months of full YardFlow deployment across their facility network.',
 *     },
 *     {
 *       type: 'cta',
 *       cta: {
 *         type: 'modex-meeting',
 *         headline: 'See what a standardized yard network looks like for The Home Depot',
 *         subtext: 'We map your top 3 facilities, identify the throughput constraint, and build a board-ready rollout plan.',
 *         buttonLabel: 'Book a Meeting at MODEX',
 *         calendarLink: BOOKING_LINK,
 *       },
 *       closingLine: 'One conversation. Your yard network. A clear path to $5M-$8M in annual savings.',
 *     },
 *   ]
 */

export const theHomeDepot: AccountMicrositeData = {
  slug: 'the-home-depot',
  accountName: 'The Home Depot',
  parentBrand: 'The Home Depot',
  vertical: 'retail',
  tier: 'Tier 2',
  band: 'C',
  priorityScore: 77,

  pageTitle: 'YardFlow for The Home Depot - Yard Network Standardization',
  metaDescription: 'How YardFlow eliminates the yard bottleneck across The Home Depot\'s facility network.',

  sections: [],

  people: [
    {
      personaId: 'P-031',
      name: 'John Deaton',
      firstName: 'John',
      lastName: 'Deaton',
      title: 'Executive Vice President – Supply Chain & Product Development',
      company: 'The Home Depot',
      email: 'john.deaton@homedepot.com',
      linkedinUrl: 'https://corporate.homedepot.com/page/home-depot-leadership-0',
      roleInDeal: 'routing-contact',
      seniority: 'C-level',
      function: 'Supply Chain',
      currentMandate: 'Official top supply-chain executive.',
      bestIntroPath: 'Executive outreach',
    },
    {
      personaId: 'P-032',
      name: 'John Drake',
      firstName: 'John',
      lastName: 'Drake',
      title: 'Senior Vice President – Supply Chain',
      company: 'The Home Depot',
      email: 'john.drake@homedepot.com',
      linkedinUrl: 'https://corporate.homedepot.com/bio/john-drake-senior-vice-president-supply-chain',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Transportation / Delivery',
      currentMandate: 'Official transportation and direct-to-customer delivery owner.',
      bestIntroPath: 'Executive outreach',
    },
    {
      personaId: 'P-033',
      name: 'Amit Kalra',
      firstName: 'Amit',
      lastName: 'Kalra',
      title: 'Senior Vice President – Supply Chain',
      company: 'The Home Depot',
      email: 'amit.kalra@homedepot.com',
      linkedinUrl: 'https://corporate.homedepot.com/bio/amit-kalra-senior-vice-president-supply-chain',
      roleInDeal: 'influencer',
      seniority: 'VP',
      function: 'Distribution / Fulfillment',
      currentMandate: 'Official distribution and fulfillment operations owner.',
      bestIntroPath: 'Executive outreach',
    },
    {
      personaId: 'P-034',
      name: 'Richard McPhail',
      firstName: 'Richard',
      lastName: 'McPhail',
      title: 'Executive Vice President & Chief Financial Officer',
      company: 'The Home Depot',
      email: 'richard.mcphail@homedepot.com',
      linkedinUrl: 'https://mx2026.mapyourshow.com/8_0/sessions/session-details.cfm?scheduleid=223',
      roleInDeal: 'routing-contact',
      seniority: 'C-level',
      function: 'Finance / Strategy',
      currentMandate: 'Official MODEX keynote speaker from Home Depot and strategic route into supply-chain priorities.',
      bestIntroPath: 'Conference outreach',
    },
    {
      personaId: 'P-035',
      name: 'Erin Donnelly',
      firstName: 'Erin',
      lastName: 'Donnelly',
      title: 'Senior Director, Supply Chain Development',
      company: 'The Home Depot',
      email: 'erin.donnelly@homedepot.com',
      linkedinUrl: 'https://www.linkedin.com/in/erin-donnelly-ga',
      roleInDeal: 'routing-contact',
      seniority: 'VP',
      function: 'Supply Chain Strategy',
      currentMandate: 'Named supply-chain development leader for transformation lane.',
      bestIntroPath: 'LinkedIn / Sales Nav',
    },
    {
      personaId: 'P-076',
      name: 'Jacquelyn Singleton',
      firstName: 'Jacquelyn',
      lastName: 'Singleton',
      title: 'Supply Chain Professional',
      company: 'The Home Depot',
      roleInDeal: 'routing-contact',
      seniority: 'Manager',
      function: 'Supply Chain',
      currentMandate: 'Engaged with FreightRoll outreach. Active signal makes this a warm routing path into Home Depot supply chain.',
      bestIntroPath: 'Direct - engaged contact',
    },
    {
      personaId: 'P-077',
      name: 'Joseph Orndoff',
      firstName: 'Joseph',
      lastName: 'Orndoff',
      title: 'Supply Chain Professional',
      company: 'The Home Depot',
      roleInDeal: 'routing-contact',
      seniority: 'Manager',
      function: 'Supply Chain',
      currentMandate: 'Engaged with FreightRoll outreach. Second warm signal at Home Depot strengthens the routing path.',
      bestIntroPath: 'Direct - engaged contact',
    },
    {
      personaId: 'P-078',
      name: 'Robert Grazian',
      firstName: 'Robert',
      lastName: 'Grazian',
      title: 'Senior Director, Supply Chain',
      company: 'The Home Depot',
      roleInDeal: 'decision-maker',
      seniority: 'VP',
      function: 'Supply Chain',
      currentMandate: 'Senior Director level at Home Depot supply chain. Decision-maker authority for yard operations tooling.',
      bestIntroPath: 'LinkedIn / warm route via engaged contacts',
    },
  ],

  personVariants: [
    {
      person: {
        personaId: 'P-031',
        name: 'John Deaton',
        firstName: 'John',
        lastName: 'Deaton',
        title: 'Executive Vice President – Supply Chain & Product Development',
        company: 'The Home Depot',
        email: 'john.deaton@homedepot.com',
        roleInDeal: 'routing-contact',
        seniority: 'C-level',
        function: 'Supply Chain',
      },
      fallbackLane: 'ops',
      label: 'John Deaton - Executive Vice President – Supply Chain & Product Development',
      variantSlug: 'john-deaton',

      framingNarrative: 'John, the question is whether a network this large can keep tolerating site-by-site yard variance.',
      openingHook: 'MODEX makes the timing relevant, so this page is framed as a short private brief rather than a pitch.',
      stakeStatement: 'Every minute of excess dwell time at The Home Depot\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'John, 200+ facilities. Every DC type runs its own yard. The variance tax across that network is massive.',
        subheadline: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'John, let\'s walk your yard network',
        subtext: '30-minute conversation about The Home Depot\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'John',
        personContext: 'Official keynote tie gives unusually strong event signal.',
      },

      toneShift: 'Strategic, board-level. Reference John\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with John\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-032',
        name: 'John Drake',
        firstName: 'John',
        lastName: 'Drake',
        title: 'Senior Vice President – Supply Chain',
        company: 'The Home Depot',
        email: 'john.drake@homedepot.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Transportation / Delivery',
      },
      fallbackLane: 'logistics',
      label: 'John Drake - Senior Vice President – Supply Chain',
      variantSlug: 'john-drake',

      framingNarrative: 'John, the question is whether transportation throughput is still losing time in the yard before anyone sees it in the network metrics.',
      openingHook: 'MODEX makes the timing relevant, so this page is framed as a short private brief rather than a pitch.',
      stakeStatement: 'Every minute of excess dwell time at The Home Depot\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'John, the transportation network you run moves 10,000 trailers a day. The yard is where that throughput stalls.',
        subheadline: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'John, let\'s walk your yard network',
        subtext: '30-minute conversation about The Home Depot\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'John',
        personContext: 'Official keynote tie gives unusually strong event signal.',
      },

      toneShift: 'Operator-to-operator. John lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['turn time', 'detention cost', 'dwell time', 'on-time pickup', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with John\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-033',
        name: 'Amit Kalra',
        firstName: 'Amit',
        lastName: 'Kalra',
        title: 'Senior Vice President – Supply Chain',
        company: 'The Home Depot',
        email: 'amit.kalra@homedepot.com',
        roleInDeal: 'influencer',
        seniority: 'VP',
        function: 'Distribution / Fulfillment',
      },
      fallbackLane: 'executive',
      label: 'Amit Kalra - Senior Vice President – Supply Chain',
      variantSlug: 'amit-kalra',

      framingNarrative: 'Amit, the question is whether four facility types are still running four different yard playbooks inside one network.',
      openingHook: 'MODEX makes the timing relevant, so this page is framed as a short private brief rather than a pitch.',
      stakeStatement: 'Every minute of excess dwell time at The Home Depot\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Amit, RDCs, SDCs, flatbed DCs, fulfillment centers. Four facility types, four yard playbooks. One should work everywhere.',
        subheadline: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Amit, let\'s walk your yard network',
        subtext: '30-minute conversation about The Home Depot\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Amit',
        personContext: 'Official keynote tie gives unusually strong event signal.',
      },

      toneShift: 'Operator-to-operator. Amit lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'detention cost', 'throughput', 'operational efficiency'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Amit\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-034',
        name: 'Richard McPhail',
        firstName: 'Richard',
        lastName: 'McPhail',
        title: 'Executive Vice President & Chief Financial Officer',
        company: 'The Home Depot',
        email: 'richard.mcphail@homedepot.com',
        roleInDeal: 'routing-contact',
        seniority: 'C-level',
        function: 'Finance / Strategy',
      },
      fallbackLane: 'cfo',
      label: 'Richard McPhail - Executive Vice President & Chief Financial Officer',
      variantSlug: 'richard-mcphail',

      framingNarrative: 'Richard, the question is whether the lowest-cost supply chain improvement left is still hiding in the yard layer.',
      openingHook: 'MODEX makes the timing relevant, so this page is framed as a short private brief rather than a pitch.',
      stakeStatement: 'Every minute of excess dwell time at The Home Depot\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Richard, you are keynoting MODEX 2026 on supply chain investment. The yard is the lowest-cost, highest-impact layer left.',
        subheadline: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Richard, let\'s walk your yard network',
        subtext: '30-minute conversation about The Home Depot\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Richard',
        personContext: 'Official keynote tie gives unusually strong event signal.',
      },

      toneShift: 'Strategic, board-level. Reference Richard\'s mandate and transformation context. Lead with outcomes and business impact, not features.',
      kpiLanguage: ['cost per load', 'detention spend', 'labor cost per trailer', 'total cost of ownership'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Richard\'s operational reality.',
    },
    {
      person: {
        personaId: 'P-035',
        name: 'Erin Donnelly',
        firstName: 'Erin',
        lastName: 'Donnelly',
        title: 'Senior Director, Supply Chain Development',
        company: 'The Home Depot',
        email: 'erin.donnelly@homedepot.com',
        roleInDeal: 'routing-contact',
        seniority: 'VP',
        function: 'Supply Chain Strategy',
      },
      fallbackLane: 'ops',
      label: 'Erin Donnelly - Senior Director',
      variantSlug: 'erin-donnelly',

      framingNarrative: 'Erin, the question is whether the last unstandardized layer in the network is still the yard.',
      openingHook: 'MODEX makes the timing relevant, so this page is framed as a short private brief rather than a pitch.',
      stakeStatement: 'Every minute of excess dwell time at The Home Depot\'s facilities erodes the margin your team is working to protect.',

      heroOverride: {
        headline: 'Erin, supply chain development means standardizing the unstandardized. The yard is the last unstandardized layer.',
        subheadline: 'Strongest public MODEX signal. Massive retail network makes execution variance expensive.',
      },
      sectionOrder: ['hero', 'problem', 'stakes', 'proof', 'solution', 'network-map', 'roi', 'testimonial', 'cta'],
      ctaOverride: {
        type: 'modex-meeting',
        headline: 'Erin, let\'s walk your yard network',
        subtext: '30-minute conversation about The Home Depot\'s yard operations and where YardFlow fits.',
        buttonLabel: 'Book a Meeting at MODEX',
        calendarLink: BOOKING_LINK,
        personName: 'Erin',
        personContext: 'Official keynote tie gives unusually strong event signal.',
      },

      toneShift: 'Operator-to-operator. Erin lives in the operational details. Lead with metrics, turn times, and facility-level impact.',
      kpiLanguage: ['truck turn time', 'dock utilization', 'throughput per shift', 'detention cost', 'carrier satisfaction'],
      proofEmphasis: 'The headcount-neutral customer quote resonates with Erin\'s operational reality.',
    },
  ],

  proofBlocks: [
    {
      type: 'metric',
      stats: [
        { value: '24', label: 'Facilities Live', context: 'Measured across live deployments' },
        { value: '>200', label: 'Contracted Network', context: 'Contracted for rollout across comparable verticals' },
        { value: '48-to-24', label: 'Min Truck Turn Time', context: 'Average improvement in drop-hook cycle' },
        { value: '$1M+', label: 'Per-Site Profit Impact', context: 'Measured at retail facilities' },
      ],
    },
    {
      type: 'quote',
      quote: {
        text: 'The yard used to be where we lost visibility. Now it is where we gain control over every trailer in the network.',
        role: 'Operations Director',
        company: 'National Retail Distributor',
      },
    },
  ],

  network: {
    facilityCount: '200+',
    facilityTypes: ['Rapid Deployment Centers', 'Stocking Distribution Centers', 'Direct Fulfillment Centers', 'Flatbed Distribution Centers'],
    geographicSpread: 'North America',
    dailyTrailerMoves: '10,000+ across network',
    fleet: 'Heavy 3PL and contract carrier; flatbed, dry van, and LTL mix',
  },

  freight: {
    primaryModes: ['Truckload', 'LTL', 'Intermodal'],
    avgLoadsPerDay: '10,000+',
    peakSeason: 'Official keynote tie gives unusually strong event signal.',
  },

  signals: {
    modexAttendance: 'Past attendee + keynote',
    recentNews: [
      'Official keynote tie gives unusually strong event signal.',
    ],
    supplyChainInitiatives: ['Strongest public MODEX signal. Massive retail network makes execution variance expensive.'],
    urgencyDriver: 'Official keynote tie gives unusually strong event signal.',
  },

  theme: {
    accentColor: '#F97316',
    backgroundVariant: 'dark',
  },

  showcase: true,
  showcaseOrder: 2,
  layoutPreset: 'retail',
};
