import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

const DEFAULT_SECRET = 'local-e2e-seed';
const ACCOUNT_FAILED = 'E2E Failed Logistics';
const ACCOUNT_GUARDED = 'E2E Guarded Warehouse';
const ACCOUNT_NO_RECIPIENT = 'E2E No Recipient Yard';
const TEST_ACCOUNTS = [ACCOUNT_FAILED, ACCOUNT_GUARDED, ACCOUNT_NO_RECIPIENT];

function unauthorized() {
  return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
}

function ensureSeedAccess(req: NextRequest) {
  if (process.env.NODE_ENV === 'production') return false;
  const expected = process.env.E2E_SEED_SECRET ?? DEFAULT_SECRET;
  const header = req.headers.get('x-e2e-seed-secret');
  return header === expected;
}

function onePagerContent(accountName: string, headline: string) {
  return JSON.stringify({
    headline,
    subheadline: `Deterministic proof content for ${accountName}`,
    painPoints: ['Queue drift', 'Version mismatch risk'],
    solutionSteps: ['Validate guard state', 'Queue async send', 'Track job status'],
    outcomes: ['Higher send confidence', 'Operationally visible status'],
    proofStats: ['2.0x faster operator review'],
    customerQuote: 'Proof-mode content is deterministic and repeatable.',
    bestFit: 'Ops and logistics stakeholders',
    publicContext: 'Generated by deterministic e2e seed.',
  });
}

export async function POST(req: NextRequest) {
  if (!ensureSeedAccess(req)) return unauthorized();

  const now = new Date();
  const old = new Date(now.getTime() - 20 * 60 * 1000);

  await prisma.$transaction(async (tx) => {
    await tx.sendJobRecipient.deleteMany({
      where: { account_name: { in: TEST_ACCOUNTS } },
    });
    await tx.sendJob.deleteMany({
      where: {
        recipients: {
          some: { account_name: { in: TEST_ACCOUNTS } },
        },
      },
    });
    await tx.emailLog.deleteMany({
      where: { account_name: { in: TEST_ACCOUNTS } },
    });
    await tx.generatedContent.deleteMany({
      where: { account_name: { in: TEST_ACCOUNTS } },
    });
    await tx.generationJob.deleteMany({
      where: { account_name: { in: TEST_ACCOUNTS } },
    });
    await tx.persona.deleteMany({
      where: { account_name: { in: TEST_ACCOUNTS } },
    });
    await tx.account.deleteMany({
      where: { name: { in: TEST_ACCOUNTS } },
    });

    for (const [index, name] of TEST_ACCOUNTS.entries()) {
      await tx.account.create({
        data: {
          rank: 900 + index,
          name,
          parent_brand: name,
          vertical: 'Logistics',
          signal_type: 'E2E',
          why_now: 'Deterministic e2e seed account',
          primo_angle: 'Proof suite validation',
          best_intro_path: 'Ops leadership',
          icp_fit: 4,
          event_signal: 3,
          primo_story_fit: 4,
          warm_intro: 2,
          strategic_value: 3,
          meeting_ease: 2,
          priority_score: 76,
          priority_band: 'A',
          tier: 'Tier 1',
          owner: 'Casey',
        },
      });
    }

    await tx.persona.createMany({
      data: [
        {
          persona_id: 'e2e-failed-ops',
          account_name: ACCOUNT_FAILED,
          priority: 'P1',
          name: 'Jordan Ops',
          title: 'VP Operations',
          email: 'jordan.ops@example.com',
          persona_status: 'Not started',
          do_not_contact: false,
        },
        {
          persona_id: 'e2e-guarded-ops',
          account_name: ACCOUNT_GUARDED,
          priority: 'P1',
          name: 'Alex Yard',
          title: 'Director of Yard Operations',
          email: 'alex.yard@example.com',
          persona_status: 'Not started',
          do_not_contact: false,
        },
      ],
    });

    const failedGenerated = await tx.generatedContent.create({
      data: {
        account_name: ACCOUNT_FAILED,
        content_type: 'one_pager',
        tone: 'professional',
        provider_used: 'ai_gateway',
        version: 1,
        is_published: true,
        published_at: now,
        content: onePagerContent(ACCOUNT_FAILED, 'Failed Account One-Pager'),
      },
      select: { id: true },
    });

    const guardedGenerated = await tx.generatedContent.create({
      data: {
        account_name: ACCOUNT_GUARDED,
        content_type: 'one_pager',
        tone: 'professional',
        provider_used: 'ai_gateway',
        version: 2,
        is_published: true,
        published_at: now,
        content: onePagerContent(ACCOUNT_GUARDED, 'Guarded Account One-Pager'),
      },
      select: { id: true },
    });

    await tx.generatedContent.create({
      data: {
        account_name: ACCOUNT_GUARDED,
        content_type: 'one_pager',
        tone: 'professional',
        provider_used: 'openai',
        version: 1,
        is_published: false,
        content: onePagerContent(ACCOUNT_GUARDED, 'Guarded Account Legacy Draft'),
      },
    });

    await tx.generatedContent.create({
      data: {
        account_name: ACCOUNT_NO_RECIPIENT,
        content_type: 'one_pager',
        tone: 'professional',
        provider_used: 'ai_gateway',
        version: 1,
        is_published: true,
        published_at: now,
        content: onePagerContent(ACCOUNT_NO_RECIPIENT, 'No Recipient Account One-Pager'),
      },
    });

    await tx.generationJob.createMany({
      data: [
        {
          account_name: ACCOUNT_FAILED,
          content_type: 'one_pager',
          status: 'failed',
          retry_count: 1,
          error_message: 'Deterministic seeded failure',
          completed_at: now,
        },
        {
          account_name: ACCOUNT_GUARDED,
          content_type: 'one_pager',
          status: 'pending',
          retry_count: 0,
        },
        {
          account_name: ACCOUNT_FAILED,
          content_type: 'one_pager',
          status: 'processing',
          retry_count: 0,
          started_at: old,
        },
      ],
    });

    const pendingJob = await tx.sendJob.create({
      data: {
        status: 'pending',
        requested_by: 'E2E Proof',
        total_recipients: 1,
      },
      select: { id: true },
    });

    const partialJob = await tx.sendJob.create({
      data: {
        status: 'partial',
        requested_by: 'E2E Proof',
        total_recipients: 2,
        sent_count: 1,
        failed_count: 1,
        started_at: old,
        completed_at: now,
      },
      select: { id: true },
    });

    const stuckSendJob = await tx.sendJob.create({
      data: {
        status: 'processing',
        requested_by: 'E2E Proof',
        total_recipients: 1,
        started_at: old,
      },
      select: { id: true },
    });

    await tx.sendJobRecipient.createMany({
      data: [
        {
          send_job_id: pendingJob.id,
          generated_content_id: guardedGenerated.id,
          account_name: ACCOUNT_GUARDED,
          persona_name: 'Alex Yard',
          to_email: 'alex.yard@example.com',
          subject: 'Seeded pending send',
          body_html: '<p>Pending seeded body</p>',
          status: 'pending',
          idempotency_key: `e2e-pending-${pendingJob.id}`,
        },
        {
          send_job_id: partialJob.id,
          generated_content_id: failedGenerated.id,
          account_name: ACCOUNT_FAILED,
          persona_name: 'Jordan Ops',
          to_email: 'jordan.ops@example.com',
          subject: 'Seeded partial send (sent)',
          body_html: '<p>Sent seeded body</p>',
          status: 'sent',
          idempotency_key: `e2e-partial-sent-${partialJob.id}`,
          sent_at: now,
          attempted_at: now,
          hubspot_engagement_id: 'seeded-engagement-1',
        },
        {
          send_job_id: partialJob.id,
          generated_content_id: failedGenerated.id,
          account_name: ACCOUNT_FAILED,
          persona_name: 'Jordan Ops',
          to_email: 'jordan.ops+failed@example.com',
          subject: 'Seeded partial send (failed)',
          body_html: '<p>Failed seeded body</p>',
          status: 'failed',
          error_message: 'Seeded deterministic failure',
          idempotency_key: `e2e-partial-failed-${partialJob.id}`,
          attempted_at: now,
        },
        {
          send_job_id: stuckSendJob.id,
          generated_content_id: guardedGenerated.id,
          account_name: ACCOUNT_GUARDED,
          persona_name: 'Alex Yard',
          to_email: 'alex.yard+stuck@example.com',
          subject: 'Seeded stuck send',
          body_html: '<p>Stuck seeded body</p>',
          status: 'sending',
          idempotency_key: `e2e-stuck-${stuckSendJob.id}`,
          attempted_at: old,
        },
      ],
    });
  });

  return NextResponse.json({
    success: true,
    accounts: TEST_ACCOUNTS,
  });
}
